### ISSUE TITLE
Long function call/declaration/array fixer: chop down list.

### ISSUE THREAD

**Issue by Strate** [PHP-CS-Fixer/PHP-CS-Fixer#2325]
Hey all. I look for fixer, which would convert this one:

```php
public function someMethid(ContainerInterface $container, MapperInterface $mapper, MatcherInterface $matcher, FooInterface $foo, BooInterface $Boo);
```

to this one:

```php
public function someMethid(
    ContainerInterface $container,
    MapperInterface $mapper,
    MatcherInterface $matcher,
    FooInterface $foo,
    BooInterface $Boo
);
```

This could be called "chop_down_if_long_fixer". similar issues are: long if condition statements, long array initializers, long function call statements and others.

Is there some thing that do this in PHP-CS-Fixer? Is it applicable to it?

**Comment by keradus** [comment]
There is no rules like that currently

**Comment by localheinz** [comment]
I would use it!

**Comment by keradus** [comment]
feel free to contribute!

**Comment by SpacePossum** [comment]
> "chop_down_if_long_fixer"

:-1:  IMHO the method/function signature fixing to multi line should be a config option of the `function_declaration` fixer (same as done for class definitions).

> similar issues are: long if condition statements, long array initializers

awesome, I would say 2 new fixers:
`condition_statement_fixer` (better name needed) -> config for long to multi line with option where to set the comparison operators (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1795).

> long array initializers
nice idea :)

ref.: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/111, https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2168

**Comment by VincentLanglet** [comment]
> This could be called "chop_down_if_long_fixer". similar issues are: long if condition statements, long array initializers, long function call statements and others.

It's unclear what is a long function declaration.
I think the config will require a length parameter.

**Comment by julienfalque** [comment]
A sensible default could be 120, which is [PSR-12's soft limit](https://www.php-fig.org/psr/psr-12/#23-lines). By the way, I think we can start with a hardcoded value first and see later if making it configurable is a common need.

**Comment by Wirone** [comment]
The fixer that should do it is `method_argument_space`, but unfortunately it does not break such signature down even with `ensure_fully_multiline` strategy. It's triggered when there's at least one new line within parameters, though:

![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/496edf8f-6585-4f72-b023-5e9a939d16b9)

I am going to close this one because it has high cognitive load (it is 7 years old and there is a lot of comments). **If anyone is still interested in having this feature**, please create new issue with feature request: ability to enforce multiline in `method_argument_space`.
