### ISSUE TITLE
Annotation with `@` is broken when using `phpdoc_inline_tag_normalizer`

### ISSUE THREAD

**Issue by fsevestre** [PHP-CS-Fixer/PHP-CS-Fixer#2513]
Hi guys,

I'm on PHP 5.6, using `friendsofphp/php-cs-fixer` on version 2.0.0, on a Symfony 3.2.3 project.

When I run the following command:
`./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix ./src/ --rules=@Symfony`

the fixer breaks an annotation.

Before:
```php
<?php

class Foo
{
    /**
     * @Route("/conventions/@{idcc}", name="api_v1_convention_read_by_idcc")
     */
    public function bar() {}
}
```

After:
```php
<?php

class Foo
{
    /**
     * @Route("/conventions/{@id cc}", name="api_v1_convention_read_by_idcc")
     */
    public function bar() {}
}
```

**Comment by fsevestre** [comment]
Other example:
`@Route("/conventions/@{id}", ...` -> `@Route("/conventions/{@id}", ...`

But:
`@Route("/conventions/@{cid}", ...` don't change.

**Comment by SpacePossum** [comment]
Confirmed on 2.x, this is done by the `phpdoc_inline_tag` fixer.
@fsevestre you might want to disable that rule while the issue is not resolved.

**Comment by SpacePossum** [comment]
I propose to remove the fixing of `@{id}` to `{@id}` as this fixing is the root cause of the issue here.
I think it is the only likely case that is being fixed that conflicts with SF annotations and is not a case that needs fixing that much for valid cases (i.e. PSR5 annotations done wrong).
I theory all fixed 'word's (example|id|internal|inheritdoc|link|source|toc|tutorial) are effected, however I don't see any of those (besides 'id') used much within SF.
The alternative would be modifying the fixer in a way that it detects that the annotation is part of a SF one (or doctrine for that matter) and not fix it. However I don't see what logic can be used to do so.

**Comment by Wirone** [comment]
FYI: Still here in 3.16, but rule causing this is `phpdoc_inline_tag_normalizer`.

<img width="895" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/449777ea-ab0d-4258-a095-757a7be74a85">
