### ISSUE TITLE
Indented extends & implements

### ISSUE THREAD

**Issue by SignpostMarv** [PHP-CS-Fixer/PHP-CS-Fixer#2553]
* php: 7.1.1
* php-cs-fixer: 2.1.0
* command: php ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --verbose --dry-run
* config: [in gist](https://gist.github.com/SignpostMarv/21a2db7eb422dd328226d139835c0c92)
* .php_cs: [in gist](https://gist.github.com/SignpostMarv/21a2db7eb422dd328226d139835c0c92)

I've just been updating the config for a project I work on & ran into a bit of an issue with the `'class_definition'` fixer; When running against itself, 2.1.0 won't let me indent the extends keyword.

In 1.12, I got around this by specifying `'-class_definition'`, but I'd like to enforce `'multiLineExtendsEachSingleLine'`, since I've been doing that for a while out of habit.

Additionally, when I add interfaces into the mix, I end up with 
```php
interface Foo
{
}

class Config extends BaseConfig implements
        Foo
{
}
```

When what I want is this:
```php

interface Foo
{
}

class Config
    extends
        BaseConfig
    implements
        Foo
{
}
```

I'm wondering if I should try to patch in additional configuration option for `'class_definition'`, or if  `'singleItemSingleLine' => false` should be considered sufficient to allow extends & implements to be on it's own line.

**Comment by SpacePossum** [comment]
Thanks for reporting, nice to hear how you use the fixer and your thoughts on how it can be improved.

Currently we have no fixer or option on a fixer that will put the keyword `extends` and `implements` on its own line. This is because [PSR2 #extends and implements](http://www.php-fig.org/psr/psr-2/#extends-and-implements) states: "The extends and implements keywords MUST be declared on the same line as the class name."
Your FR is to add a way to diff. from PSR2 (this is not a problem on itself, we have more fixers that deviate from the PSR's), which would require to modify the `class_definition` fixer.
I wonder how often this CS is used. It i important to this project to know if more projects use the style rule as if so it is more likely we get help maintaining the fixer in the future.

In remark of `won't let me indent the extends keyword.` this is another missing feature. I think this would require changes to the `braces` fixer. Not sure for now if this a general rule we miss or only the `implements` and `extends` keywords. Would be interesting to investigate further.

**Comment by SignpostMarv** [comment]
Sounds like if I were to try patching a rule in, it'd be to add something like `'blank_line_before_extends'` & `'blank_line_before_implements'` to the PSR-2 ruleset & default it to false or have it configurable as `'none'` or `'one'` ?

**Comment by SignpostMarv** [comment]
ran into a bit of an issue. seems if I specify `['@PSR2' => true, '@Symfony' => true]` that I can't also specify `'class_defintion'`

**Comment by SignpostMarv** [comment]
I seem to have [fixed my use case, but broken the phpunit tests :(](https://github.com/SignpostMarv/PHP-CS-Fixer/tree/fix/issue-2553), assistance would be appreciated :)

**Comment by SignpostMarv** [comment]
@SpacePossum @Wirone haven't worked at the place where this level of finnickiness was necessary (better job now, much more mellow outlook), happy to have this closed/rejected 🤷‍♂️

**Comment by Wirone** [comment]
Thank you @SignpostMarv for the info, I'll close it then since it did not get any interest from the users 🙂.
