### ISSUE TITLE
Fixer for multiline annotations

### ISSUE THREAD

**Issue by edhgoose** [PHP-CS-Fixer/PHP-CS-Fixer#2698]
As per the conversation in #2682, I'd like to see a new fixer to turn annotations that contain multiple components into a multiline annotation.

In our code base, this is common with Doctrine and Assert indexes.

As an example, here is an example of what one line of our code base looks like:

```php
     * @Assert\Choice(choices={ClassOfConstants::CONST_A,
     *                           ClassOfConstants::CONST_B,
     *                           ClassOfConstants::CONST_C,
     *                           ClassOfConstants::CONST_D,
     *                           ClassOfConstants::CONST_E,
     *                           ClassOfConstants::CONST_F}, message="long.message.key.for.validation.message.error", groups={"Creation"})
```

I'd love a Fixer that can make it something similar to:

```php
     * @Assert\Choice(
     *     choices={
     *          ClassOfConstants::CONST_A,
     *          ClassOfConstants::CONST_B,
     *          ClassOfConstants::CONST_C,
     *          ClassOfConstants::CONST_D,
     *          ClassOfConstants::CONST_E,
     *          ClassOfConstants::CONST_F
     *     }, 
     *     message="long.message.key.for.validation.message.error", 
     *     groups={"Creation"}
     * )
```

Or here's another one with Doctrine annotations (names changed, obvs):

```php
 * @ORM\Table(
 *     name="fruit",
 *     indexes={
 *  @ORM\Index(name="fruit_discr", columns={"discr"}),
 *  @ORM\Index(name="fruityness_type", columns={"FruitType"}),
 * })
 * @ORM\Entity(repositoryClass="fruit\FruitBundle\Entity\Repository\FruitRepository")
 * @ORM\InheritanceType("SINGLE_TABLE") @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *     "abstract_fruit" = "Fruit", "banana_fruit" = "BananaFruit", "apple_fruit" = "AppleFruit",
 *     "orange_fruit" = "OrangeFruit","pinapple_fruit" = "PinappleFruit"
 * })
 * @ORM\HasLifecycleCallbacks
```

I think this should be something like:

```php
 * @ORM\Table(
 *     name="fruit",
 *     indexes={
 *         @ORM\Index(name="fruit_discr", columns={"discr"}),
 *         @ORM\Index(name="fruityness_type", columns={"FruitType"}),
 * })
 * @ORM\Entity(repositoryClass="fruit\FruitBundle\Entity\Repository\FruitRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *     "abstract_fruit" = "Fruit",
 *     "banana_fruit" = "BananaFruit",
 *     "apple_fruit" = "AppleFruit",
 *     "orange_fruit" = "OrangeFruit",
 *     "pinapple_fruit" = "PinappleFruit"
 * })
 * @ORM\HasLifecycleCallbacks
```

I think, but I'm very much unsure, that the rules are something like:

- Annotations containing multiple lines and/or a long string of text between opening and closing brackets should be split across multiple lines
- Options within an annotation should also be split across multiple lines if they too contain many options (i.e. in the case above, the bit between `choices={` and `}`
- Indentation should be applied to every sub item (e.g. a `choices={}` or a `@Indexes(`)
- Brackets and braces should be on the same line as the beginning of the annotation, or they should be on their own line

I think it's very similar to the Indentation fixer, but with a few extra pieces. I'm not sure whether it should be implemented as a new fixer or as part of that fixer.

I haven't quite got to grips with the code base for fixers yet so not sure I could complete this, but I'd be glad to write a set of unit tests to help someone else.

**Comment by julienfalque** [comment]
> Annotations containing multiple lines and/or a long string of text between opening and closing brackets should be split across multiple lines

I think we should apply the same rule than with PSR-2: annotations arguments or array values may be split accross multiple lines, but with only one value per line. In such case, the first and last values must be on their own line instead of next to opening/closing parenthesis/brace. When this rule is violated, the fixer should move each value to its own line. An array or nested annotation on mulitple lines should not force the parent annotation to be multiple lines as well. For example, this would be valid:

```php
/**
 * @Foo("foo", {
 *     "bar"
 * }, "baz")
 */
```

Not sure we should also check content's length as it might be very difficult to decide what is the best element to span on multiple lines with nested elements. This choice should be left to users as they might prefer to rewrite another element for e.g. readability reasons.

> Options within an annotation should also be split across multiple lines if they too contain many options (i.e. in the case above, the bit between choices={ and }

Like with content's length, this might be difficult. For example, an array may contain a lot of very short values:

```php
/**
 * @Foo({0, 1, 2, 3, 4, 5, 6, 7, 8, 9})
 */
```

This case is perfectly fine to me and should not be changed. But on the other hand, there might be cases where you have only a few long values:

```php
/**
 * @Foo({"Some long string that exceeds a content length limit, like for example 80 characters", "Another long string that exceeds a content length limit, like for example 80 characters"})
 */
```

This one would be a good candidate for multiple lines values. So relying on the number of values is not enough IMO.

> Indentation should be applied to every sub item (e.g. a choices={} or a @Indexes()

👍 

> Brackets and braces should be on the same line as the beginning of the annotation, or they should be on their own line

👍 (should be handled by the `doctrine_annotation_spaces` fixer as well).

Like you said, these rules are partially covered by other fixers. Don't know what's the best to do here:
1. not handle indentation in this new fixer and let the existing one handle it;
2. refactor so that code can be shared between those fixers via a helper or something.

I'd vote for 2 though :)

**Comment by julienfalque** [comment]
Since PHP 8 introduced attributes, I think we can safely assume annotations usage is going to decrease a lot. Not sure working on this would be worth it. What's your opinion @kubawerlos @keradus @SpacePossum @localheinz?

**Comment by mbrodala** [comment]
@juliendufresne The same request applies to attributes however. Is there already a way to enforce (aligned) multi-line formatting for PHP attributes?

**Comment by julienfalque** [comment]
As far as I know we don't have any rule handling attributes specifically.

**Comment by Richard87** [comment]
As we are using Api-Platform and use alot of long attributes, this feature would help us a lot!

For example this:
```php
#[ApiResource(collectionOperations: [
'get',
'post' => [
    'input' => CreateDoctorDto::class,
    'controller' => CreateDoctor::class,
],
], itemOperations: [
'get',
'api_update_doctor_profile' => [
    'method' => 'POST',
    'path' => '/doctors/{id}/update_profile',
    'input' => UpdateProfileDto::class,
    'controller' => UpdateProfile::class,
],
'api_update_doctor_doctor' => [
    'method' => 'POST',
    'path' => '/doctors/{id}/update_doctor',
    'input' => UpdateDoctorDto::class,
    'controller' => UpdateDoctor::class,
],
'api_update_doctor_office' => [
    'method' => 'POST',
    'path' => '/doctors/{id}/update_office',
    'input' => UpdateOfficeDto::class,
    'controller' => UpdateOffice::class,
],
], shortName: 'Doctor', normalizationContext: ['groups' => ['Doctor:details']], security: "is_granted('ROLE_ADMIN')"
)]
class Doctor {
```
Is completley fine by PHP-CS-Fixer, but is terrible to look at, so I spend quite a bit of time to manually clean this

**Comment by localheinz** [comment]
@edhgoose 

Sounds great!

I currently fix a lot of this manually, as per my latest article [Wrapping it up](https://localheinz.com/blog/2021/12/31/wrapping-it-up/#content-annotations) on my blog.

**Comment by nedvajz** [comment]
May help to someone. I was able to solve many of problems like this with Prettier  
  
Usually I do use in this order
1. rector
2. prettier (https://github.com/prettier/plugin-php)  
3. phpcs (ecs)

**Comment by Wirone** [comment]
@Richard87 attributes are PHP code and it's totally different thing than annotations, which are parsed comments, using external library. Current fixers should handle syntax inside attributes, but if they don't please file separate issue.

---

I am going to close this because:
- it's 6 years long, without implementation
- PHP8 with attributes was released in the meantime, and that's the direction in which community goes with modern code. There's no point in investing time in really complex annotation handling when we should just focus on promoting attributes. @julienfalque already [suggested it 2 years ago](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/2698#issuecomment-841814394), now it's even more valid.
- core team won't work on it, so it does not make sense to keep it open. 

Anyway, if you feel you would like to implement this - [go ahead](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/CONTRIBUTING.md#how-to-contribute)! We would happily review and merge it, if the quality of implementation is good enough for further maintenance 🙂.
