### ISSUE TITLE
SpaceShip <=> fixer

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#2795]
```diff
-$a > $b ? -1 : 1
+$a <=> $b
```

**Comment by julienfalque** [comment]
The new line is not strictly equivalent to the old one: `$a <=> $b` will return `0` when `$a == $b`. How would we deal with such case?

**Comment by keradus** [comment]
I bet we could write proper specification for fixer to see is it possible to automate this change in that case ;)

**Comment by gharlan** [comment]
> The new line is not strictly equivalent to the old one

The new line is the opposite of the old one (with addition of `0`).
@keradus I guess you mean `$a > $b ? 1 : -1` ;)

**Comment by Slamdunk** [comment]
Minor idea: the fixer could be configured to substitute `strcmp` function too (ref https://secure.php.net/manual/en/function.strcmp.php)

**Comment by Wirone** [comment]
Have you ever had actual need for spaceship operator usage? Honest question, I never used it in my life 🙂. Does it make sense to invest effort to build such fixer? Since it's a three-way operator returning very specific set of values, there should be rather something like this:

```php
$a === $b ? 0 : ($a > $b ? 1 : -1);
```

How many time did you see such code 😅?

In my opinion there's no point in doing this.

**Comment by Slamdunk** [comment]
> Does it make sense to invest effort to build such fixer?
No
> Have you ever had actual need for spaceship operator usage?
Dozens of times every month, when ordering arrays with usort

**Comment by Wirone** [comment]
I am going to close this one because effort required to create such fixer largely overweight the outcome. There's no point in keeping it open, it's been 6 years already without implementation.

**Comment by keradus** [comment]
good call @Wirone 
6 years :D
