### ISSUE TITLE
Bug: selfupdate command doesn't check PHP version

### ISSUE THREAD

**Issue by makss** [PHP-CS-Fixer/PHP-CS-Fixer#3178]
```
$ php -v
PHP 5.5.38 (cli) (built: Jul 21 2016 12:51:12) 

$ php-cs-fixer
PHP CS Fixer version 1.10 by Fabien Potencier (8e21b4f)

$ php-cs-fixer selfupdate
php-cs-fixer updated.

$ php-cs-fixer
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.2.*.
```
It's unpleasant.
I restored the old version of PHP-CS-Fixer from the backup.

**Comment by keradus** [comment]
it doesn't check it indeed.
I must admit it's not most prio thing ,but if you want, please open a PR to fix it.

**Comment by keradus** [comment]
oh, even better. you are using 1.10. 1.12 was last release of PHP CS Fixer and it's already abandoned for a year.

Please update it to 2.x (2.2.x supports PHP 5.3, so it's fine for you).
We do have a guideline how: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.7/UPGRADE.md, and if sth won't be clear, reach us at gitter channel: https://gitter.im/PHP-CS-Fixer/Lobby/

**Comment by makss** [comment]
@keradus thanks for the answer. I put version 2.2.7, everything is fine, but when it is updated, it also dies.

I added the Pull request #3179, please check.

**Comment by Wirone** [comment]
I believe we can close this issue because:
- we don't support v1 and v2 versions
- in v3, `self-update` command by default updates only minor versions (needs `--force` to bump major), so it's safe to run it in terms of Fixer's API
- [PHP version bumps are not a BC-break in terms of SemVer](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html), so after upgrading runtime on user's side everything should work as before
- when upgrading PHAR, there's previous version in the output (like `PHP CS Fixer updated (3.16.0 -> v3.17.0)`), so it's easy to go back to previous version by downloading PHAR from that release
- there was little to no interest in this for past 6 years

Anyway, feel free to provide PR that solves this and it can be reviewed, but core team won't work on it.
