### ISSUE TITLE
Fixer for removing redundant ternary operator

### ISSUE THREAD

**Issue by EvgenyOrekhov** [PHP-CS-Fixer/PHP-CS-Fixer#3486]
When the first operand produces a boolean value, and the second and the third are `true` and `false` respectively:

```diff
-$a = $b === $c ? true : false;
+$a = $b === $c;
```

```diff
-$a = $b !== $c ? true : false;
+$a = $b !== $c;
```

```diff
-$a = $b > $c ? true : false;
+$a = $b > $c;
```

...and other comparison operators.

**Comment by ntzm** [comment]
Would be risky if `true` or `false` was overwritten by `use const`

**Comment by keradus** [comment]
> `define true false`, happy debugging...

**Comment by ntzm** [comment]
Seeing as this fixer would already be risky, what about inbuilt functions that return a boolean?

```diff
-is_array($a) ? true : false;
+is_array($a);
```

**Comment by ntzm** [comment]
You could also extend it to add a typecast in cases where the expression beforehand doesn't evaluate to a boolean:

```diff
-strpos($a, $b) ? true : false;
+(bool) strpos($a, $b);
```

Thoughts?

**Comment by SpacePossum** [comment]
`is_array($a) ? true : false;`
always results in a boolean (with the exception when overriding `true`|`false` but I don't care about that case to much)

`is_array($a);`
does not always, as `is_array` could've been overridden.
Besides, you would've to list all build in PHP functions that return a boolean, or at the `(bool)` cast everywhere (and than we need a fixer to remove not needed bool-casts ;) )

I think maybe it is best to start with the expressions and think about the function cases in a different `issue` / `PR`.

**Comment by Wirone** [comment]
I am going to close this one because:

- it's 5 years old, if it wasn't implemented this long, it means it's not actually that needed
- I believe it fits better for PHPStan/Psalm as these tools have the scope context for types, function/method signatures etc. Even if we hardcoded all PHP's built-in functions with `bool` return value, the fixer wouldn't cover all the cases becase custom methods could be involved too (like `Foo::bar() ? true : false`, where `bar(): bool`)
- scope of this issue is too wide (considering comments)
- implementation is not trivial (especially considering [this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3486#issuecomment-362515869)) with little to no gain
- IDE plugins like [PHP inspections](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) can point such needless code and automate refactoring

Summing this up, there is more downsides of this than upsides 🙂.
