### ISSUE TITLE
MethodChainingIndentationFixer: fix call contents

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#3558]
For this snippet:

```php
$foo = $bar
            ->baz([
                1 => 2,
            ])
->xyz()
;
```

following https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3528 currently `MethodChainingIndentationFixer` does:

```diff
 $foo = $bar
-            ->baz([
+    ->baz([
                 1 => 2,
             ])
-->xyz()
+    ->xyz()
 ;
```
What I would like is:

```diff
 $foo = $bar
-            ->baz([
-                1 => 2,
-            ])
+    ->baz([
+        1 => 2,
+    ])
-->xyz()
+    ->xyz()
 ;
```

**Comment by julienfalque** [comment]
:+1: 

It should also do this:

```diff
 $foo
-        ->bar([
-                1 => 2,
-            ])
-                ->baz()
+    ->bar([
+            1 => 2,
+        ])
+    ->baz()
;
```

i.e. the indentation of the array should be adjusted, not fixed. I did the same in #3135.

**Comment by Slamdunk** [comment]
> i.e. the indentation of the array should be adjusted, not fixed.

I agree, but what would you do on this?

```php
$foo
    ->bar()            // ok
        ->baz([        // will go back by 4 spaces
            1 => 2     // will go back by 4 spaces
])                     // how to handle this?
;
```

**Comment by julienfalque** [comment]
We could either:
* not change the indentation of the array because, as a whole, it already has the minimum indentation (so moving the `->baz([` row only)
* unindent all possibles lines (like most IDEs would do when selecting the array and pressing `Shift+Tab`), the array would be actually changed, not ajusted, but the indentation is already wrong anyway

I personally prefer the second choice.

**Comment by Slamdunk** [comment]
> I personally prefer the second choice.

Me too

**Comment by Slamdunk** [comment]
@julienfalque the `has PR` label should be removed at the time of writing

**Comment by julienfalque** [comment]
Indeed, thanks :)

**Comment by Wirone** [comment]
Closing, because as of now Fixer 3.16 does exactly what is expected

<img width="896" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/7da90a59-6463-4e11-bbc6-4c6f182d56db">

I believe indentation of an array is better like this, which is like in @Slamdunk's initial report.
