### ISSUE TITLE
Replace inline docblock declarations with assertions

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#3648]
Taken from https://github.com/doctrine/coding-standard/pull/47 by @Ocramius

```diff
-/** @var Type $simpleType */
 $simpleType = expression();
+assert($simpleType instanceof Type);
```

What do you think?

**Comment by EvgenyOrekhov** [comment]
Great idea. I have an experience with replacing all inline docblock declarations with assertions in our latest project. The benefit of using assertions is that their support in IDEs and static analyzers is much better than support of docblocks. Although that fixer would be risky if you forget to turn off assertions in production.

**Comment by Ocramius** [comment]
> would be risky if you forget to turn off assertions in production.

As discussed in doctrine/coding-standard#47, no risk involved, as these assertions should always hold true. If that's not the case, then getting an error is a good thing.

**Comment by keradus** [comment]
well, sounds easy to be done. feel free to propose a PR ;)

hint: I would let removal of phpdoc be optional, as more tools can read from phpdoc than from assert

**Comment by SpacePossum** [comment]
>no risk involved

A typo in a PHPDoc about the type will cause no problems during execution/runtime, the assert will stop executing if left on. So this is still risky I think.

**Comment by Ocramius** [comment]
> will cause no problems during execution/runtime

You don't change and deploy code (not even code blocks) without:

 1. going through static analysis
 2. going through tests

Projects not doing (1) and (2) should worry about these before considering using any CS fixing tool.

**Comment by keradus** [comment]
Well, CS Fixer is no longer CS tool since v2, it's SCA tool as well ;)

I do find reasoning of @SpacePossum valid.
What does our `risky` label means? Simply, that meaning of code could be different after applying changes, the outcome of execution may be different. And even if phpdoc was valid (in terms of lack of typos), but wrong (eg `int` instead of `string`), the assertion will fail, causing code to work differently. This is perfect reason to mark fixer as risky. In fact, most (if not all) SCA rules in PHP CS Fixer are risky.
This rule may reveal error in codebase. If it didn't, it's great, no error faced, great, but still, it may. It's also great, just deserves a `risky` indicator.
@Ocramius , I totally agree about your 1&2 points, but giving ppl some indicator that they shall not apply such rule out of the blue on codebase with poor tests (Eg legacy projects) is must have imho.

**Comment by Wirone** [comment]
FYI: there's [`PhpdocVarAnnotationToAssertFixer`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#phpdocvarannotationtoassertfixer) from @kubawerlos's Custom Fixers repository.

**Comment by Wirone** [comment]
I believe we can close this as there wasn't any movement here for 5 years before my previous comment, after it too, so it seems like there's no longer need for this, and even if people need it, then it's already possible to use such [fixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#phpdocvarannotationtoassertfixer). Maybe @kubawerlos can move it to the core in the future 🙂.
