### ISSUE TITLE
Merge/Simplify PhpUnitMethodCasingFixer & PhpUnitTestAnnotationFixer code

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#3896]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3886#issuecomment-403624977

[PhpUnitMethodCasingFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3886) shares 80% of the code with [PhpUnitTestAnnotationFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3275), they should be merged/simplified in the code (but not in the functionalities, e.d.)

**Comment by Wirone** [comment]
I am going to close this issue. Even though that's true these fixers share some code (mostly `isTestMethod()` method, but not only), I don't think keeping this issue open makes much sense. It's been 5 years without direct fix for this, but both fixers were modified several times through the years and their body diverged more. If anyone is willing to make refactoring, then PR is welcome, but we don't need issue for that since it's not crucial improvement.
