### ISSUE TITLE
PHPDoc indent do not remove trailing whitespace

### ISSUE THREAD

**Issue by dennisdahlc** [PHP-CS-Fixer/PHP-CS-Fixer#3998]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.1

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:
```php
=> 'phpdoc_indent' => true
``` 

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
=> <?       /** @var ClassName $className */        ?>
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> <? /** @var ClassName $className */        ?>
```

 * with the changes you expected instead:
```php
=> <? /** @var ClassName $className */ ?>
```
The PhpDoc indent fixer only removes leading whitespaces and not trailing.

Would it be possible to perform a similar operation for the trailing whitespaces or at least have an option for it ?

**Comment by Wirone** [comment]
Please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), that's why I'm going to close this report. Feel free to provide PR, but we can't assure it will be merged anyway.

Also, this issue refers to Fixer's version which is not maintained anymore.
