### ISSUE TITLE
[Feature Request] Order private and protected methods by their internal call order

### ISSUE THREAD

**Issue by ntzm** [PHP-CS-Fixer/PHP-CS-Fixer#4080]
Got the idea from: https://old.reddit.com/r/PHP/comments/9uny1g/how_geeky_do_you_sort_private_methods/ cc @TomasVotruba 

For example:

```php
class A {
    public function a() { $this->c(); }
    private function b() { echo 'hi'; }
    private function c() { $this->b(); }
}
```

would turn into

```php
class A {
    public function a() { $this->c(); }
    private function c() { $this->b(); }
    private function b() { echo 'hi'; }
}
```

**Comment by SpacePossum** [comment]
I would like to see all methods ordered alphabetically (after visibility) ;) Anyway, nice to see people care and think about this ordering.

Is the suggestion a standard that is used a lot?

**Comment by dmvdbrugge** [comment]
I know it is one of the options PhpStorm offers in their formatting.
Don't know how much used it actually is.

**Comment by TomasVotruba** [comment]
This is the fixer: https://github.com/Symplify/Symplify/blob/master/packages/CodingStandard/README.md#order-private-methods-by-their-use-order

**Comment by cwhsu1984** [comment]
I would love to see this feature implemented too!

**Comment by Wirone** [comment]
Personally I don't see any value in such ordering - IDE can search methods, navigate back and forth through them (I recommend `cmd+[` / `cmd+]` shortcuts). How such ordering would help? Also, I'm afraid it would introduce too much noise because changing methods' implementation could require methods' reordering, which does not make sense to me.

As far as I see, `PrivateMethodOrderByUseFixer` was [deprecated](https://github.com/symplify/symplify/pull/1911), and then probably removed, because it's not included in [`symplify/coding-standard`](https://github.com/symplify/coding-standard/tree/main/src/Fixer). For me, it indicates that such fixer did not work in practice, and I believe it's a good reason to close this feature request. @TomasVotruba would you mind providing info about that?

Anyway, if anyone is still interested in this, feel free to provide reasoning and we can always reopen this 🙂.
