### ISSUE TITLE
Require phpdoc/docblock for all functions

### ISSUE THREAD

**Issue by kkmuffme** [PHP-CS-Fixer/PHP-CS-Fixer#4137]
Is there a way to check/require phpdoc/docblock for all functions?
I wasn't able to find anything in the docs, but just want to be sure

**Comment by SpacePossum** [comment]
Hi @kkmuffme 

Currently we've rules to fix or make PHPDoc more complete, however we don't have one to make sure there is one for each function.

**Comment by kkmuffme** [comment]
Ok then I'd like to suggest it as a feature since it would the existing filters more complete & also makes a lot of sense in my opinion.

**Comment by ttomdewit** [comment]
Am I correct to understand this feature request will add Docblocks to all function currently without a Docblock?

Thanks for your time,.

**Comment by kkmuffme** [comment]
Yes.

I moved to php codesniffer, which already supports this

**Comment by nessor** [comment]
Any news on this?

**Comment by SpacePossum** [comment]
AFAIK nobody worked on this in the repo

**Comment by Wirone** [comment]
I believe after 5 years since initial request it got outdated, considering PHP going more and more into strict types (signatures, properties, even class constants) it does not make sense to promote phpDoc for all functions/methods. IDEs read native signatures and attributes, and don't need annotations for proper autocompletion and validation. We even have fixer for removing superfluous phpDoc. That's why I am going to close this one as core team won't work on it.

Anyone interested in this feature: feel free to propose PR, we can consider adding it 🙂.
