### ISSUE TITLE
`no_unused_imports` - allow keeping imports from the same namespace

### ISSUE THREAD

**Issue by arnaud-lb** [PHP-CS-Fixer/PHP-CS-Fixer#4159]
The `no_unused_imports` fix is removing imports of the same namespace.

Removing imports of the same namespace can be harmful: It makes it more difficult to move the code in an other namespace later (because we have to make sure that all classes have been imported).

**And more importantly**, if a class is _implicitly_ imported, it's easy to accidentally shadow it by importing an other class with the same name from an other namespace.

Also, imports are free (in terms of performance), so imports of the same namespace are not really an issue.

I believe that stopping this behaviour, and maybe adding a new fix that imports all used classes, would result in code that's safer to edit.

**Comment by arnaud-lb** [comment]
Since a _feature request_ tag has been added, I've submitted a PR to disable this behaviour by default: #4243. I will also submit a fixer that imports all used classes, later in a separate PR.

**Comment by kubawerlos** [comment]
> It makes it more difficult to move the code in an other namespace later (because we have to make sure that all classes have been imported).

I wouldn't consider it as an issue, it does not seems to be problem for any modern IDE.

> **And more importantly**, if a class is _implicitly_ imported, it's easy to accidentally shadow it by importing an other class with the same name from an other namespace.

What do you mean? Something like [this](https://3v4l.org/e8DXZ):
```php
<?php
namespace Foo;
class Test { const FROM = 'foo'; }

namespace Bar;
class Test { const FROM = 'bar'; }

namespace Foo;
use Bar\Test;
echo Test::FROM;
```
?

**Comment by arnaud-lb** [comment]
> What do you mean? Something like this:

Probably. Just to be sure that we are speaking of the same thing, let's say that we have this code:

```
<?php
// Foo/Hello.php

namespace Foo;

class Hello
{
    public function __construct(Request $request)
    {
        ...
    }
}
```

Notice that `Foo/Hello.php` is not importing `Request`. This is not absolutely required, because PHP will default to using the current namespace. So, `Request` implicitly refers to `Foo\Request` (which was the intent, so it's ok).

Later, in the same file, we want to use `Symfony\Component\HttpFoundation\Request`. So we type `$httpFoundationRequest = new Request()`, and make the steps to import `Request`.

This is where troubles can happen: If you import `Symfony\Component\HttpFoundation\Request` as `Request`, the line `public function __construct(Request $request)` that refered to `Foo\Request` now refers to `Symfony\Component\HttpFoundation\Request`.

We have shadowed `Foo\Request`, and now the code probably doesn't work anymore.

I believe that this threat is caused by the lack of explicit import of `Foo\Request`, and could be avoided by explicitly importing every class.

**Comment by GPHemsley** [comment]
It seems the discussion around this issue has been mostly negative (particularly in #4243, the PR intending to improve the situation), I'd like to explicitly voice my support for this, as I found the behavior confusing and unexpected (see #5168). In particular, I think it is misleading to call an import "unused" simply because it is potentially redundant, and I think @arnaud-lb makes an excellent case above that an explicit import of a class in the same namespace is not in fact redundant at all.

It seems there is a strong opinion in favor of being able to remove imports from the same namespace, but if that's the case, I think it would be beneficial to developers like me and Arnaud to be able to define that separately from truly unused imports imports. In fact, I would even go so far as to say that such setting should allow an option to automatically _add_ missing explicit imports from the same namespace - which would be even more useful given that the current behavior is to automatically remove them, even if the developer intentionally put them there.

I didn't look too deeply into the proposed implementation, but it seemed there was some concern about breaking backwards compatibility by changing the behavior of `no_unused_imports`, but if a new option was implemented whose default value was to remove explicit imports from the same namespace, wouldn't that suffice?

**Comment by SpacePossum** [comment]
Looking back at the PR and the discussion I think there were a few (3) issues with it. 

So all have valid arguments whether or not it is good practice to do one thing or the other. As such the discussion did not conclude to go one way for all parties. It is good to hear from more people like you about what their preference is. That way we as members know more about how populair something is.

That itself weights heavy in the project because of two reasons.
The scope of the project is to help people fix code to a coding standard. We support a bunch of standards and also rules that are considered best practices by bigger (FOSS) communities. However, the scope of the project is not to deliver a generic code styling tool that can be configured to fix to any style (it can be done by using custom or 3rd party rules).
Secondly, the more popular a feature is the bigger our changes we will get people helping out maintaining it, which is vital to the project (which is for example why we lack wordpress rules; even though it is a big community it is using different tooling)

Last thing about the PR was the target branch. It should've been `master` so it could ship with 2.17 and not with next 2.15 patch. This is because of our BC promise / semantic versioning, but that was the least important issue with PR I think.

Looking at the voting of the PR it was very close, it shows various view from contributors and members. I also know that arguments about what is populair, what is a code style/rule or the weight of the feature against the maintenance cost, can seem arbitrary. It hard to avoid; maintenance can't be really calculated as we don't know the future and code styles come and go in and out of fashion. 

We try to balance and reason as best we can and at times revisit FR's and PR's. As such I feel this request can still stay open and maybe we can do check to see how everybody feels about the request now, it been a year so who knows :)

**Comment by peter-at-bpt** [comment]
For the record

> it does not seems to be problem for any modern IDE.

is a terrible argument in favor of this behavior.

1. Not everyone uses an IDE. "An IDE can..." is never the beginning to a valid argument regarding features in CLI tools.
2. It doesn't matter what the IDE does, this still introduces the possibility of naming collision.

Scenario

Today: I'm in `namespace MyApp;` , class 'Foo`. I add a call to `MyApp\Bar`. `php-cs-fixer` decides FOR ME that this is an unused import because it's in the same directory.
A year later: Someone else adds a new class `NewNamespace\Bar`, they add it into the `Foo` class and import it. `php-cs-fixer` decides for them that this isn't an unused import.

All references that were supposed to call `MyApp\Bar` now call `NewNamespace\Bar`, a functional change made because of a decision made by a code-linting tool.

Yes, I understand that tests, QA, etc can handle this but they also might not or might not exist. The linter has in effect changed the functionality of the app / introduced bugs or Exceptions because it's not _necessary_ for the import to exist, not because not importing is a _good_ idea or follows some standard.

This behavior should be optional and NOT conflated with `no-unused-imports`.

Our only rational choice at this point is to turn off `no-unused-import` and consider the behavior bugged until this changes.

**Comment by kubawerlos** [comment]
> For the record
> 
> > it does not seems to be problem for any modern IDE.
> 
> is a terrible argument in favor of this behavior.
> 
> 1. Not everyone uses an IDE. "An IDE can..." is never the beginning to a valid argument regarding features in CLI tools

I totally agree, please notice however that the argument was made regarding to "move the code in an other namespace later", not using any CLI tool.


> A year later: Someone else adds a new class `NewNamespace\Bar`, they add it into the `Foo` class and import it. `php-cs-fixer` decides for them that this isn't an unused import.
> 
> All references that were supposed to call `MyApp\Bar` now call `NewNamespace\Bar`, a functional change made because of a decision made by a code-linting tool.

If I add the import it means I now expect the imported class to be used, so "All references that were supposed to call `MyApp\Bar` now call `NewNamespace\Bar`" is absolutely what I expect, because I've just added the import.

> a functional change made because of a decision made by a code-linting tool

who added the import? Developer or code-linting tool? ^^


> I understand that tests, QA, etc can handle this but they also might not or might not exist.

I'd suggest focusing on writing some tests then, instead of caring about coding standards ;)

> The linter has in effect changed the functionality of the app / introduced bugs or Exceptions because it's not _necessary_ for the import to exist, not because not importing is a _good_ idea or follows some standard.

Did that happened to anyone? I'm coding in PHP for more years I'm comfortable to admit and never encounter such a situation.

> This behavior should be optional and NOT conflated with `no-unused-imports`.

Used -> needed for code to work.
Unused -> not needed e.g. imports from the same class.

> Our only rational choice at this point is to turn off `no-unused-import` and consider the behavior bugged until this changes.

Personally, I would consider the behaviour bugged if it was not removing imports from the same space and I would extend the fixer as a custom one.


Last, but not least - is it the practice of not removing imports from the same namespace part of any well-recognized standard?

**Comment by GPHemsley** [comment]
I don't think it's fair to the discussion to consider the OP's example as only the argument for a change in behavior, when others of us in the thread have offered different arguments for the same point. I also don't think it's appropriate to base an argument on "it's never happened to me before, so it hasn't happened to anybody" or "if you coded better, you wouldn't have this problem".

The discussion is about a command-line utility that performs automatic changes to a codebase. Multiple individuals have independently expressed surprise at its behavior. I think it is based on this fact that the discussion should be evaluated.

In particular, it is clear that much of the argument hinges on the meaning of the word "unused". To those of us objecting to the current behavior, there is a difference between _an import statement that imports a class that is not called_ and _an import statement that imports a class that would otherwise be imported implicitly_. To ignore this distinction, or claim it doesn't exist, is disingenuous.

Given the aforementioned distinction, I reiterate my support for the splitting of the current `no-unused-import` into 2 rules. The argument that this would increase maintenance burden is, IMHO, a weak one, given that the code already exists in the current rule: the only new code would be the scaffolding needed to separate it out into a new rule.

In addition, there have been multiple appeals to the idea of a well-recognized or widely-supported coding standard as justifying the current behavior or discouraging the proposed behavior, but none have been named explicitly. What coding standard argues against the splitting of the current behavior into 2 separate rules that can be configured independently?

**Comment by kubawerlos** [comment]
You don't like arguments based on observation:
> I also don't think it's appropriate to base an argument on "it's never happened to me before, so it hasn't happened to anybody" or "if you coded better, you wouldn't have this problem".

yet, you are making one by yourself:
> Multiple individuals have independently expressed surprise at its behavior.

Let's do some simple calculations:
 - "Multiple individuals" would be the author of this issue and all upvoted - that makes `6`,
 - the fixer was added over 8 years ago

That makes less than 1 person per year, not what I understand by "multiple individuals" ;)

> What coding standard argues against the splitting of the current behavior into 2 separate rules that can be configured independently?

The question is (since the beginning) what coding standard requires the behaviour this issue is about? Or is that even [good practice](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4243#issuecomment-461403309)?

Following approach "What coding standard argues against" I can ask if you are adding at the end of each file comment "I made this with smile", becaue I bet there is no standard no to do that ;)

**Comment by SpacePossum** [comment]
So what did they say at Pint? That it should be fixed here and they will republish the effort done here under their name?

**Comment by Wirone** [comment]
@arnaud-lb @GPHemsley is this issue valid after few years? Would you still expect to have explicit imports from the same namespace?

@thebazshah are you sure? It doesn't seem like it's related.

**Comment by Pixelao** [comment]
I wanted to express my support for this approach. Having imports from the same namespace can be beneficial in some cases. My team deliberately employs this method.

In my opinion, this behavior should be configurable; maybe not the default option, but at least there should be an option to choose.
