### ISSUE TITLE
Require `@covers` for Codeception Cept classes

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#4510]
Hi, code coverage annotations as proposed by PHPUnit (see https://phpunit.readthedocs.io/en/8.3/annotations.html#covers) are use also outside PHPUnit scope, as the parser is written to be namespace/library agnostic:
https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Test.php#L131

In fact Codeception uses this to give users the ability to write the same annotations for Cest tests:
https://github.com/Codeception/Codeception/blob/379e6d4c25947e5e2c467c24edc31e3665c0ec8f/src/Codeception/Test/Cest.php#L208

To me `PhpUnitTestClassRequiresCoversFixer` is really valuable, and I would like to use its features also for Cest tests.

The fixer for Cest files would be identical to `PhpUnitTestClassRequiresCoversFixer`.

A simple flag in `PhpUnitTestClassRequiresCoversFixer` would be misleading to me.

A clean solution may be to create a new class and proxy  `PhpUnitTestClassRequiresCoversFixer` and the Cest one to a shared logic.

`PhpCsFixer\Indicator\PhpUnitTestCaseIndicator` is out of scope: no other fixers can be applied to Codeception too; `PhpUnitOrderedCoversFixer` isn't tight to `PhpUnitTestCaseIndicator` so it already fixes Codeception Cept tests.

WDYT?

Side note: `PHPUnit\Util\Test` is declared `@internal`, so Codeception could have to drop the feature in the future while still present in PHPUnit; not much an issue for us, but it's better to know this.

**Comment by SpacePossum** [comment]
So why is the fixer not usable-as-is, is it because of PhpUnitTestCaseIndicator::isPhpUnitClass check?

**Comment by Slamdunk** [comment]
Yes, but changing it would change the behavior of other fixers as well, and that shouldn't happen

**Comment by SpacePossum** [comment]
Indeed, changing that shouldn't be done. Not sure how to proceed though.

**Comment by Slamdunk** [comment]
A flag on `PhpUnitTestCaseIndicator::isPhpUnitClass` would be a start, avoiding code duplication and raising awareness among fixers and developers, wdyt?

**Comment by Wirone** [comment]
> A flag on `PhpUnitTestCaseIndicator::isPhpUnitClass` would be a start, avoiding code duplication and raising awareness among fixers and developers, wdyt?

Since there's explicit `PhpUnit` in the name, I think it's not a good idea to put Codeception support there. It should be either:
- renamed to `TestCaseIndicator`, so `isPhpUnitClass()` would do the same, but we could add `isCodeceptionClass()`
- kept as-is, and new `CodeceptionTestCaseIndicator` could be introduced

In both cases some common logic could be extracted (to private method within the same class or to some abstract base class).

**Comment by keradus** [comment]
Hey! I'm closing this as there is no traffic around anymore since 2019 (Except one msg from core team).

The idea could be valid, yet it didn't get any movement around.

If any of you see a value in it and are ready to implement it, please draft mini-RFC what you would like to achieve and how.



Also, @Wirone , if you see value and chance that this will somehow get implemented after those years of having it not prioritised, feel free to re-open it.
