### ISSUE TITLE
GlobalNamespaceImportFixer needs option to ignore types on doc blocks

### ISSUE THREAD

**Issue by hackel** [PHP-CS-Fixer/PHP-CS-Fixer#4854]
Currently the GlobalNamespaceImportFixer tries to import classes from phpdoc annotations, even if they aren't actually used in the code.  This is an issue when your coding style dictates that you always use FQCNs in doc blocks only.  I don't want it to use the imported class name or import unnecessary classes.  

Ideally, it would also have an option to rewrite it to use the FQCN, but that should probably be a separate rule. (functions y and z below)

 * before running PHP CS Fixer (no changes):
```php
<?php
namespace Test;

use Exception;

/** @throws \Throwable */
function x() {}

/** @throws Throwable */
function y() {}

/** @throws Exception */
function z() {}
```

 * with the changes you expected instead:
```php
<?php
namespace Test;

use Exception;

/** @throws \Throwable */
function x() {}

/** @throws \Test\Throwable */
function y() {}

/** @throws \Exception */
function z() {}
```

**Comment by Wirone** [comment]
You can achieve what you want for `function z()` by configuring `global_namespace_import` with `"import_classes": false`:

<img width="1024" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/8028125e-019e-4f59-9047-eb8156a61657">

Keep in mind that it will also un-import native types too:

<img width="1024" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/eaac4c87-5203-411f-b894-b03f90e67adb">

What you want for `function y()` is out of the scope of this fixer because it's about **global namespace**, while `\Test\Throwable` is from custom namespace.

That's why I am going to close this issue (and because there was 0 interest in it for 3 years).
