### ISSUE TITLE
A SuperfluousPhpdocParamFixer

### ISSUE THREAD

**Issue by dennisdahlc** [PHP-CS-Fixer/PHP-CS-Fixer#5057]
## Feature request

So

    /**
     * Login user
     *
     * @param Object $loginData
     * @param Object $userData
     *
     * @throws Exception
     *
     * @return object $response
     */
    private function loginUser($loginData)

becomes

    /**
     * Login user
     *
     * @param Object $loginData
     *
     * @throws Exception
     *
     * @return object $response
     */
    private function loginUser($loginData)

**Comment by kubawerlos** [comment]
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3734

**Comment by dennisdahlc** [comment]
Why is this marked as a duplicate?
The proposed fixer in #3734 do no remove unused param doc on the php doc at all.

**Comment by julienfalque** [comment]
It does. There also is a option to disable this behavior specifically: `allow_unused_params`.

**Comment by dennisdahlc** [comment]
The problem is that I only want the 'allow_unused_params' => false behavior, but there are phpdoc removed which I do not have removed.

`    /*
     * @param array $session
     */
    private function verify_session(array $session)
    {`

becomes

`    /*
     */
    private function verify_session(array $session)
    {`

which I do not want. I only want the fixer to remove unused parameters and nothing else.

**Comment by kubawerlos** [comment]
@dennisdahlc then it looks like [this](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#PhpdocNoSuperfluousParamFixer) fixer, am I right?

For `no_superfluous_phpdoc_tags` we would need a new option like `allow_superfluous_phpdoc_tags`, but that would be quite silly as the goal of the fixer is to remove superfluous PHPDoc tags.

**Comment by mvorisek** [comment]
This issue should be probably closed.

**Comment by Wirone** [comment]
I am going to close this issue because:
- there wasn't any activity for 3 years (not counting @mvorisek's comment)
- with PHP's development during years community focuses more and more around native types and there's no point in duplicating signature's info in phpDoc (hence `no_superfluous_phpdoc_tags`). The only cases where additional phpDoc makes sense is when it actually provides additional information (like generics, array shapes). As a Fixer team we encourage native types usage, with them annotations in phpDoc are just... well, superfluous.
- core team has limited capacity and it's nearly impossible that anyone would work on this, especially considering previous point.
