### ISSUE TITLE
Don't modify IIFE @var blocks

### ISSUE THREAD

**Issue by eugenekunkel** [PHP-CS-Fixer/PHP-CS-Fixer#5156]
## Rule request

Don't modify IIFE (Immediately Invoked Function Expression) @var blocks

## Explanation

Sometimes I need to `include` or `require` a PHP file, with the PHP file assuming a specified set of vars have been declared. This allows the IDE to type hint a variable object as applicable, even without the object's instantiation being present in the file.

## Desired Result (Multiple @vars Declared)

```php
<?php

/** @var FooClass $foo */
/** @var BarClass $bar */
/** @var DoeClass $doe */

$foo->doSomething();

if ($foo->isSomething()) {
    $bar->doSomething($foo);
}

$doe->setFoo($foo);
```

## Current Result (Multiple @vars Declared - Needs 2 * Asterisks)

```php
<?php

/** @var FooClass $foo **/
/* @var BarClass $bar **/
/* @var DoeClass $doe */

$foo->doSomething();

if ($foo->isSomething()) {
    $bar->doSomething($foo);
}

$doe->setFoo($foo);
```
## Desired Result (Single @var Declared)

```php
<?php

/** @var FooClass $foo **/

$doe = new Doe();
$doe->setFooResult($foo->doSomething());
```
## Current Result (Single @var Declared - Needs Line Break)

```php
<?php

/** @var FooClass $foo **/
$doe = new Doe();
$doe->setFooResult($foo->doSomething());
```

**Comment by SpacePossum** [comment]
Hi and thanks for your suggestion!

Since your report is not complete I'm just going to assume this change is done by the `phpdoc_to_comment` rule :)

This rule works on PSR5 defined rules and since your code is not following that I would advice you to disable the rule in your configuration. Modifying the rule itself seems not useful to me as I would remove the one functionality it is suppose to do.

**Comment by Wirone** [comment]
@eugenekunkel There's no IIFE in your examples 🤷‍♂️. To be honest I don't fully get what your request is - you should provide code snippet before fixer run, current output and desired output, that would show the problem to solve.

I'm going to close this report, because core team has limited capacity and won't work on it. Feel free to provide PR, but we can't assure it will be merged anyway.
