### ISSUE TITLE
Fix for array braces (on the same line)

### ISSUE THREAD

**Issue by wazum** [PHP-CS-Fixer/PHP-CS-Fixer#5160]
## Support question

I found no rule to fix the following

```php
            $this->someService->updateSomething(
                [
                'id' => $something->getId(),
                'type' => Something::DOCUMENT_TYPE
            ]);
```

as

```php
            $this->someService->updateSomething([
                'id' => $something->getId(),
                'type' => Something::DOCUMENT_TYPE
            ]);
```

or to transform

```php
            $this->someService->updateSomething(
                [
                    'id' => $something->getId(),
                    'type' => Something::DOCUMENT_TYPE
                ]
            );
```

into the much preferred form

```php
            $this->someService->updateSomething([
                'id' => $something->getId(),
                'type' => Something::DOCUMENT_TYPE
            ]);
```

With the `'@Symfony'` rule nothing happens at all (the first example is kept as-is).
Can somebody point me in the right direction or is this missing currently and I need to issue a new rule/feature request? tia

**Comment by SpacePossum** [comment]
Hi @wazum and thank you for your question.
Currently we've don't have any rule for this, therefore I changed this issue into a feature request.

**Comment by Wirone** [comment]
I believe it could be an configuration option in [`method_argument_space`](https://cs.symfony.com/doc/rules/function_notation/method_argument_space.html), something like `single_multiline_argument` with allowed values:

- `new_line`
- `same_line`

I did not name this option after `array`, because it should work also for nested function calls:

```php
foo(bar($a, $b, $c));

// with `single_multiline_argument=new_line`
foo(
    bar(
        $a,
        $b,
        $c
    )
);

// with `single_multiline_argument=same_line`
foo(bar(
    $a,
    $b,
    $c
));
```

Why "single line argument"? Because if there are multiple arguments, it does not make sense to stick to the same line, all arguments should be nested like:

```php
foo(
    bar(
        $a,
        $b,
        $c
    ),
    baz()
);
```

Unfortunately, currently `method_argument_space` ensures multiline only if there's already new line character somewhere between `(` and `)`. Also, it skips nested calls and arrays... So implementing this feature won't be that easy 😅.
