### ISSUE TITLE
Fix name to longest imported name

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#5199]
This is a feature request.

Consider this code:
```php
<?php

use A\B;
use A\X as Y;
use S as R;
use S\T;

new \A\B();
new \A\B\C();
new \A\X();
new \A\X\Z();
new R\T();
```

curently the code is fixed to (because of `no_unused_imports` if enabled, otherwise nothing is fixed):
```php
<?php

use S as R;

new \A\B();
new \A\B\C();
new \A\X();
new \A\X\Z();
new R\T();
```

but I propose that the code is fixed to:
```php
<?php

use A\B;
use A\X as Y;
use S\T;

new B();
new B\C();
new Y();
new Y\Z();
new T();
```

ie. names are replaced with the longest imported name/part.

**Comment by Wirone** [comment]
Related to #5594 because we first need to introduce support for `new` in `fully_qualified_strict_types`. But if we focus on actual feature request here, it can be implemented for types used in parameters and return types, then it would just work for any other place where FQCNs are shortened. Please see [`topic/fqcn`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aopen+label%3Atopic%2Ffqcn+sort%3Aupdated-desc) label, there is a lot to do on this matter.
