### ISSUE TITLE
phpdoc_align rule incorrect behavior

### ISSUE THREAD

**Issue by fluffycondor** [PHP-CS-Fixer/PHP-CS-Fixer#5378]
## Bug report

PHP 7.4.13
PHP CS Fixer 2.17.1 Desert Beast

### Code snippet that reproduces the problem

  ```php
     /*
      * @var array<string, array<string, int>>
      * Something like ['Lada' => ['total' => 10, 'onDuty' => 3]]
      */
     private array $transportSummary = [];

  ```
incorrectly aligns to:
```php
     /*
      * @var array<string, array<string, int>>
-     * Something like ['Lada' => ['total' => 10, 'onDuty' => 3]]
+     *                    Something like ['Lada' => ['total' => 10, 'onDuty' => 3]]
      */
     private array $transportSummary = [];
```

**Comment by Wirone** [comment]
I've checked it with v3.16.1 and it does not modify code provided in the snippet. However, it indeed changes the indentation when `/**` is used instead of `/*`:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/600668/230320569-1e5cb02b-3fea-4849-8104-a6f6c3630830.png">

@fluffycondor what do you think Fixer should do? Do not touch that comment at all, or move it to the same line as `@var`?

**Comment by mvorisek** [comment]
should be closed as `phpdoc_align` should not touch (normal) `/*` comments

**Comment by Wirone** [comment]
Yeah, there was over one month without the feedback, so I'm going to close this one 👍.
