### ISSUE TITLE
Possibility to configure static_lambda rule for arrow functions

### ISSUE THREAD

**Issue by louisgab** [PHP-CS-Fixer/PHP-CS-Fixer#5449]
## Rule request

I think the static keyword isn't useful for short arrow functions (I'm not sure, maybe I'm wrong)...
So there should be an option to ignore it, something like:
```php
'static_lambda' => ['short_arrow' => true|false|null]
```

### Code snippet that shows how the rule would fix PHP code

The opion should not impact classic callables:
  ```php
array_map(static function($item) { // <= static keyword appended
    // some multi-line code
});
  ```
But it should change arrow functions depending on the option value
For example, if null option is specified:
  ```php
array_map(fn ($item) => // some single-line code); // <= static keyword not appended
  ```

**Comment by kubawerlos** [comment]
> I think the static keyword isn't useful for short arrow functions (I'm not sure, maybe I'm wrong)...

I'd like to see some investigation on that matter - the change itself would be very simple, but there should be a reason.

**Comment by keradus** [comment]
I'm lost in translation, probably...

> It should not (...)
> But it should not (...)

so what it should?
can you show the example of expected diff ? before and after fixing?

**Comment by louisgab** [comment]
@keradus yeah sorry now that I'm rereading it seems confused, I edited

@kubawerlos some context from documentation:
When declared in the context of a class, the current class is automatically bound to it, making $this available inside of the function's scope. If this automatic binding of the current class is not wanted, then static anonymous functions may be used instead.

Arrow functions use by-value variable binding. This is roughly equivalent to performing a use($x) for every variable $x used inside the arrow function.

**Comment by kubawerlos** [comment]
@louisgab this makes sense.

Now I wonder if there is any difference between [having](https://3v4l.org/E58Ke/vld#output) and [not having](https://3v4l.org/6Qrh1/vld#output) `static` for array functions - opcode looks the same.

**Comment by SpacePossum** [comment]
The main difference is being explicit about how the function can be used, i.e. if it can be bound to an object using https://www.php.net/manual/en/closure.bind.php or if it cannot. 

```php
<?php

class Foo
{
    public int $counter = 6;
}


$a = fn () => $this->counter + 1;
$b = static fn () => $this->counter + 1;

$f = Closure::bind($a, new Foo());
echo $f();


$f = Closure::bind($b, new Foo());
echo $f();
```

So it is as much about performance as about intended use. I'm +0 for having arrow functions as configurable.

**Comment by Wirone** [comment]
Personally I believe this is not needed at all. `static_lambda` fixer takes closure's body into consideration and `static` is added only if `$this` is not used. In terms of arrow function:

- it will be converted to static if current implementation is static and it's totally OK. If non-static usage is required later, then PHPStan can catch it if `static` is not removed (`Undefined variable: $this` if `$this` is used in closure defined as `static`)
- if such closure is then used for binding, then it won't work, but this scenario is already covered in fixer's description (that's why it's risky)

[PHP Inspections plugin](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) for PHPStorm also suggests adding `static` where `$this` is not used, so this fixer just does similar thing.

<img width="868" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/55164114-203d-4032-861e-bc06252be7a8">

Even considering binding, IDE can catch invalid operations (like `$this->counter` not available, because `$counter` is a static property).

<img width="392" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/e1a56beb-6258-4d43-8939-8cfd8d05fce1">

So in terms of code's state when fixer is applied, the outcome is exactly as expected it to be. That's why I am going to close this (and also because it's stale and did not get traction from users), but we can always reopen if other maintainers don't agree with me 🙂.
