### ISSUE TITLE
Fixers for single/multi-line PHP array/object docblock type declarations?

### ISSUE THREAD

**Issue by Ocramius** [PHP-CS-Fixer/PHP-CS-Fixer#5501]
### Context

I'm currently working on a project that heavily relies on [`vimeo/psalm`](https://github.com/vimeo/psalm) type declarations for objects/arrays.

The declarations are in following form:

```php
/**
 * @var array{
 *   foo: string,
 *   bar: string
 * }
 */
```

```php
/**
 * @var object{
 *   foo: string,
 *   bar: string
 * }
 */
```

These declarations exist for `@param`, `@var`, `@return`.

### Consistency problem

Sometimes, the above are written as single-line, making them confusing to read:

```php
/**
 * @var array{foo: string, bar: string}
 */
```

In other cases, they are unnecessarily written as multi-line, even though only one key is defined:

```php
/**
 * @var array{
 *   foo: string
 * }
 */
```

### Consistency (potential) solution

My idea is to have a fixer that, given an array-shape or object-shape docblock like the above:

 * enforces single-line declaration when only one key is present
 * enforces multi-line declaration when multiple keys are present
 * preserves formatting for types inside the keys (to be formatted recursively)

**Comment by Wirone** [comment]
Similar to #3168 and #1217 - it's not that easy to mark the line when multiline should be enforced. Items count is not enough IMHO, because you rather wouldn't want to have `@var array{int, int}` (tuple) in separate lines. In #6387 there were two separate conditions to trigger multiline and I believe for array shapes it could be pretty much the same.
