### ISSUE TITLE
Support for object initialisation in `fully_qualified_strict_types`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#5594]
## Rule request

`fully_qualified_strict_types` should shorten FQCN to imported symbols in `new \Foo\Bar()`-like cases.

### Code snippet that shows how the rule would fix PHP code

```diff
<?php

use Foo\Bar;
use Some\CustomException;

-$a = new \Foo\Bar();
+$a = new Bar();

-throw new \Some\CustomException('ohoh');
+throw new CustomException('ohoh');
```

**Comment by mvorisek** [comment]
support should be added into `fully_qualified_strict_types` fixer, all class names should be fixed by this fixer (excl. the ones in phpdoc probably)

**Comment by Wirone** [comment]
@mvorisek #7459 covers some of scenarios covered here:

- FQCNs in `catch`
- FQCNs used in static fetches/calls like `\Foo\Bar::class`, `\Foo\Bar::foo()`, `\Foo\Bar::BAR`

I believe this issue is too wide, that's why I am going to close it, but instead:
- I'll create an issue for adding support for FQCN-based calls to imported functions 
- fixing to longest imported name is already reported in #5199

If I overlooked something, let me know 🙂.

**Comment by mvorisek** [comment]
I would be happy if this issue can be kept and update the issue title for `new xxx` only.

**Comment by mvorisek** [comment]
also `$x instanceof \Ns\Cl` is not fixed currently

**Comment by Wirone** [comment]
@mvorisek support for traits is described in #7568. We don't have an issue for `instanceof`, though. In general, please see [`topic/fqcn`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Atopic%2Ffqcn) label and use single-responsibility issues instead of requesting additional scenarios in existing issues 🙂.
