### ISSUE TITLE
"Unfolding" of constructor property promotion

### ISSUE THREAD

**Issue by sebastianbergmann** [PHP-CS-Fixer/PHP-CS-Fixer#5706]
PHP 8 introduced [Constructor Property Promotion](https://wiki.php.net/rfc/constructor_promotion).

For projects that decide against the use of this feature, I would appreciate a rule that transforms

```php
<?php declare(strict_types=1);
final class C
{
    public function __construct(
        private bool $x
    ) {}
}
```

to

```php
<?php declare(strict_types=1);
final class C
{
    private bool $x;

    public function __construct(bool $x)
    {
        $this->x = $x;
    }
}
```

**Comment by kubawerlos** [comment]
Is there something wrong with the property promotion? I'd like to have a fixer making the "folding".

**Comment by Wirone** [comment]
For those who want to use property promotion, there's [custom fixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#promotedconstructorpropertyfixer) that promotes properties. I believe it would be good to support both approaches here, as built-in fixer(s).

**Comment by Wirone** [comment]
I am going to close this one because I had several discussions with @keradus about similar things and his vision about PHP CS Fixer is about promoting so-called good practices. In terms of PHP itself, I believe that "good practices" are about using newest language features, and constructor property promotion is fine example for that, because it significantly reduces amount of code required to define classes. That's why I don't think that core team will ever work on this feature request and, as I said before, for promoting properties there's already [userland alternative](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#promotedconstructorpropertyfixer).

Personally I think it would be good if Fixer could also do downgrade actions (like Rector), but it's not up to me 🤷‍♂️.
