### ISSUE TITLE
Add option to `strict_comparison` to fix comparison between strings only

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#5744]
## Feature request

Migration code to `strict_comparison` rule is one of the most time consuming task.

This is a feature request to add an option to `strict_comparison` to fix comparison between strings only.

Example:

```diff
- $a == 'a';
+ $a === 'a';
- $a != 'a';
+ $a !== 'a';
- $a <> 'a';
+ $a !== 'a';
- 'a' == $a;
+ 'a' === $a;
 $a == 1; // keep unfixed with the new option from this feature request is configured
```

When something is compared against string, the other operator side should be string as well or the comparison does not make a lot of sense.

This feature request will ease migration to strict comparisons heavily and also help with migration to PHP 8.0 as non-strict comparisons are stricter, see https://3v4l.org/cPIVQ .

**Comment by keradus** [comment]
@mvorisek , would you like to implement such extension to rule?

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek , would you like to implement such extension to rule?

Help wanted, examples from the description can be used freely of course.

**Comment by Wirone** [comment]
@mvorisek I believe this is out of scope of Fixer, it's better to catch those comparisons with PHPStan which has full analysis context (possible types of compared variable). Fixer does not know what variable carries, so if there's `$a == $b` how to determine if it should be migrated? But it could be, if both variables have string values. Also, if there's `$a == '1'`, it should be fixed with your approach, but if `$a = 1.0` it has different result when [comparing using strict comparison](https://3v4l.org/qjfCg) or [not](https://3v4l.org/RKt5c).

It could be done as risky, but personally I think we shouldn't provide such fixer.

**Comment by keradus** [comment]
I believe it is in a scope of the fixer and as much as we can automate, the better - and yes, changing each `==` into `===` is hard, and changing ones with string in use is helping to limit the number of places we need the more dangerous fix.
I was always under the impression that we are talking here about an option for comparing sth with string literal, not variable (that would require types tracking)

**Comment by Wirone** [comment]
@keradus I don't know why you've been under such impression since all examples from the feature request use variables 🙂.

**Comment by keradus** [comment]
I mean to touch `$a == 'a'` and not `$a == $b`

**Comment by Wirone** [comment]
Then, [as I said](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5744#issuecomment-1595816251), it can change how code works, so at least it must be marked as risky.

**Comment by mvorisek** [comment]
Risking this is too risky, rely on static analyser and fix it semi-manually.
