### ISSUE TITLE
Remove type part of @param annotation when they match the native type

### ISSUE THREAD

**Issue by nicolas-grekas** [PHP-CS-Fixer/PHP-CS-Fixer#5784]
We're likely going to adopt this convention: when the native type is good enough, but we still want to keep the description of the param, we'll remove the type from `@param`, eg:

![image](https://user-images.githubusercontent.com/243674/123942202-335fb280-d99b-11eb-9c13-33a7781d30de.png)

It'd be great to have a php-cs rule for that!

Not that this is "legal": https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/param.html

**Comment by keradus** [comment]
@nicolas-grekas , are you still interested in this?
if so, could you drop a PR proposal?

**Comment by Wirone** [comment]
I believe static analysis tools would complain about missing type, personally I don't see much value in this approach. I understand it's a way of providing additional info for params without (re-)defining type, because it's a way of preventing type mismatch between native type and the annotation. Curious about your reasoning @nicolas-grekas 🙂.

**Comment by nicolas-grekas** [comment]
This didn't get much taction, and generics need more detailed types quite often, so let's close.
