### ISSUE TITLE
Add ability to process from cli options more than one config and rules values

### ISSUE THREAD

**Issue by hanovruslan** [PHP-CS-Fixer/PHP-CS-Fixer#5814]
## Feature request

Hi! as i metioned in gitter [here](https://gitter.im/PHP-CS-Fixer/Lobby?at=60f6affd6ccf813819ca389b) it would be great to make fix (command `php-cs-fixer fix`) options rules or\and config be able to accept multi values

Thus some default config (provider by some vendor package) can be processed without almost any configuration and additional config for specific project/repo with its own additonal rules and sets (with higher priority) can be processed also

Furthermore default (the first config) can be updated as a traditional vendor package

**Comment by keradus** [comment]
IMHO:
- non trival rules should be stored as config file
- multiple config files can be simplified by storing them into dedicated config files.

i don't see a reason for change, yet.
you mentioned specific project/repos - can't they own have dedicated config file? that's what we are suggesting as best usage of the tool

**Comment by Wirone** [comment]
I am going to close this because:
- it's stale for 2 years without response from the author
- the requirement is not described enough IMHO
- proper place to propose such changes is [RFC section of Github Discussions](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/categories/rfc), the issue should be an outcome after reaching agreement
- if I understand this issue correctly, then I don't see a point in it: instead of passing 2+ `--rules` it could be combined to one, and for larger rule sets it's better to have config file as @keradus mentioned (no need for multiple config files too). If the issue is about mixing `--rules` with `--config` then again: I don't see the need for that, since you can just create dedicated config file.
