### ISSUE TITLE
`NoSpacesAfterFunctionNameFixer` removes whitespace between `echo` and IIFE's parenthesis

### ISSUE THREAD

**Issue by paulbalandan** [PHP-CS-Fixer/PHP-CS-Fixer#5950]
## Bug report

PHP: 8.0.10
PHP CS Fixer: v3.1.0
Configuration: 'no_spaces_after_function_name' => true

### Code snippet that reproduces the problem

```php
 <?php

echo (function () {})();
```

**Expected output:** no changes.

Actual output after running fixer:
```php
<?php

echo(function () {})();
```

**Comment by kubawerlos** [comment]
There is a test for `echo` to remove space in such situation: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/tests/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixerTest.php#L58-L75

**Comment by julienfalque** [comment]
Maybe related: #4859.

**Comment by mvorisek** [comment]
I confirm this bug, example:

```
echo ($propertyValue ? 'TRUE' : 'FALSE') . EOL;
```

**Comment by Wirone** [comment]
@kubawerlos those tests mentioned by you cover different scenarios - in all of them parentheses are part of `echo`. In @paulbalandan and @mvorisek's examples parentheses are part of the echoed statement:

- IIFE: immediately Invoked Function Expression
- ternary wrap, because `EOL` needs to be concatenated with its result

I believe in such scenarios `echo` should be treated rather like language construct (like [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.1.0/tests/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixerTest.php#L100)), than function call.

FYI: reproduced on `3.16-DEV` (current master), so still needs a fix.

**Comment by mvorisek** [comment]
this issue should not be subject to stale bot
