### ISSUE TITLE
Make constants affected by no_superfluous_phpdoc_tags

### ISSUE THREAD

**Issue by mos-ru** [PHP-CS-Fixer/PHP-CS-Fixer#5991]
## Feature request

Hello, could you consider the possibility of removing const superfluous phpdoc like this:

Before:

```php
class Foo
{
    /**
     * @var string
     */
    private const FOO = 'foo';
}
```

After:
```php
class Foo
{
    private const FOO = 'foo';
}
```

And thank you for such a great tool btw.

**Comment by julienfalque** [comment]
Makes sense to me. Would you like to contribute it?

**Comment by mos-ru** [comment]
@julienfalque Sure, I could try. Does it need any additional options, like "remove scalars and keep arrays phpdoc" ?

**Comment by julienfalque** [comment]
Mmmh I would enable this new behavior by default, without any option. @keradus @SpacePossum @kubawerlos  What do you think?

**Comment by kubawerlos** [comment]
I'd like to challenge the statement that `@var` for constant is superfluous - is it even correct? When having variable, the type in annotation is used to know how that variable can be changed, to comply with type declared in annotation.

For constant it's not the case - the type is known when it is created and will not change.

Thus such an annotation is removed with [`PhpdocNoIncorrectVarAnnotationFixer`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#PhpdocNoIncorrectVarAnnotationFixer). My proposition is to copy that fixer (which also removes wrong annotation which you can see in the sample in the link) instead of extending `no_superfluous_phpdoc_tags`.

**Comment by julienfalque** [comment]
I think `no_superfluous_phpdoc_tags` is more appropriate.

On constants, PHPDocs are either superfluous (because they repeat information that can be inferred from the values) or wrong (because they contradict with the values).

I would only remove them in case they are correct (and thus superfluous). In case of a wrong PHPDoc tag, I would keep it so that static analysis can report the error—maybe the type was correct and the value wasn't?

**Comment by mvorisek** [comment]
Yes, `no_superfluous_phpdoc_tags` should be improved to fix `@var` above constants. Also, for constants, `@const` should be fixed like as if it was `@var`.

**Comment by Wirone** [comment]
Just my 2 cents: before PHP 8.3 it's not possible to add type declaration to class-like constants, so `@var` somehow extends the contract for constants and define expected type. Since constants defined on interfaces (since 7.1) or traits (8.2), these values can be overridden in classes implementing/using those symbols. The same goes for constants defined in non-final classes. I believe removing `@var` from constants should be done only for constants that can't be overridden, otherwise it would lead to scenarios like [this](https://phpstan.org/r/0c14cf26-da34-4533-8bb9-7806cd3d268c):

```php
<?php declare(strict_types = 1);

interface Foo {
	/** @var string */
	public const FOO = 'foo';
}

interface Bar {
	public const BAR = 'bar';
}

class A implements Foo {
	public const FOO = 1;
}

class B implements Bar {
	public const BAR = 1;
}
```

PHPStan can warn about type mismatch in `A` class (because of `@var` defined in the interface), but it's totally fine with const's type change in `B`, because expected type is not defined there.

**Comment by Wirone** [comment]
I am going to close this one because taking PHP 8.3's [typed class constants](https://wiki.php.net/rfc/typed_class_constants) into consideration we should treat such `@var` annotations as pre-8.3 replacements (described [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5991#issuecomment-1647733936) too). Scenarios, where such annotation should be removed are rather edge cases (like annotation over private const or annotation over public const in final class) and IMHO it's not worth the hassle. It would be closed in few days anyway by stale bot.

If anyone would like to implement this anyway, feel free to do it, but having comments above in mind 🙂.

**Comment by Jean85** [comment]
Hi all... I stubled here because I was expecting `no_superfluous_phpdoc_tags` to apply to typed constants. Would make sense to reopen this issue now, and apply it only to typed constants where the type perfectly overlaps? 

My constants got typed thanks to Rector, so this would remove a lot of cruft automatically.

**Comment by Wirone** [comment]
@Jean85 Wouldn't it be better if Rector cleaned up after itself 🤔? I mean, if Rector takes type from phpDoc and puts it as native type for the const, it could also remove the annotation... It has access to PHPStan's doc parser, I guess it is doable.

I mean, I am not against supporting this in Fixer, but from DX point of view it would be just better if you needed only 1 run to achieve it, instead of using 2 tools sequentially.
