### ISSUE TITLE
general_phpdoc_annotation_remove won't remove Template annotation

### ISSUE THREAD

**Issue by Bilge** [PHP-CS-Fixer/PHP-CS-Fixer#6101]
## Bug report

   * PHP version: PHP 7.4.25
   * PHP CS Fixer version: PHP CS Fixer 3.2.1 Mountains

`general_phpdoc_annotation_remove` refuses to remove `@Template()` annotation, no matter what.

### Code snippet that reproduces the problem

```shell
--rules='{"general_phpdoc_annotation_remove": {"annotations": ["template", "Template", "Template()"]}}'
```

```php
<?php

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class MyController extends Controller
{
    /**
     * @Template()
     */
    public function myAction(Request $request) {}
}
```

**Comment by kayw-geek** [comment]
It does not support the annotation of "xxx ()", which is his regular expression.
[L68-L69](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/b93ee4b41b11f60d75dafa29206250e09547a614/src/DocBlock/Tag.php#L68-L69)

**Comment by Bilge** [comment]
If that regex is the only guard blocking the fixer then it would be easy to amend.

```diff
-@[a-zA-Z0-9_-]+(?=\s|$)
+@[a-zA-Z0-9_-]+(?=[\s(]|$)
```

However, it seems that `Tag` class is intended to strictly follow the format and guidelines specified by the PSR PHPDoc standard. So then the question becomes, do we want to expand the scope of that class to support community tagging/attributes style or introduce a separate class and/or fixer to handle that?

**Comment by kayw-geek** [comment]
I think there may be many similar situations, which depends on the original intention of the author's design.

**Comment by Wirone** [comment]
@Bilge yes, with your regex it works (Fixer `3.16`):

<img width="1349" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/b8bbb45a-b398-4ffd-83be-ee18856d9eac">

But I am also not sure if this particular Fixer should touch Doctrine Annotations 🤔. @kubawerlos what do you think?

**Comment by kubawerlos** [comment]
Is it about Doctrine's annotation or generally about annotations having open parenthesis after the name?

**Comment by Bilge** [comment]
Generally.

**Comment by gnutix** [comment]
I noticed `general_phpdoc_annotation_remove` doesn't seem to work for "inlined" PHPDoc either : `* {@inheritDoc}` was not removed when providing `'annotations' => ['inheritdoc'], 'case_sensitive' => false`.

**Comment by Wirone** [comment]
> Is it about Doctrine's annotation or generally about annotations having open parenthesis after the name?

> Generally.

Let's make glossary here: [Doctrine Annotations](https://github.com/doctrine/annotations) is a library for defining phpDoc-placed annotations (`@Foo()`, `@Bar\Baz()`), defined by Doctrine itself or any other vendor. At the other hand, we have [phpDoc _tags_](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md) (`@foo`, `@bar-baz`) that never went out of PSR draft. This fixer's name suggests it takes care of the former (annotations), while in fact it handles the latter (tags) 😅.

I am going to close this, because:
- adding [proposed change](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6101#issuecomment-966952174) is not enough, because Doctrine Annotations can be defined with FQCN and can be multiline. It is far more complex, and I believe core team won't work on it (really low priority).
- since Doctrine Annotations are read by that library in runtime, which Fixer is not aware of, we can't decide which are safe to remove. Even if we consider user's config as a source of truth, I believe fixer should become risky, and it's a BC break.
- Really low interest in this (2 years+ now)
