### ISSUE TITLE
configure "native_constant_invocation" to add a backslash to all constants?

### ISSUE THREAD

**Issue by nicolas-grekas** [PHP-CS-Fixer/PHP-CS-Fixer#6191]
On Symfony, we recently updated to php-cs-fixer 3 and fabbot is trying to remove the `\` in front of eg `APC_ITER_KEY`.
Of course, apcu is not installed on the server that runs fabbot.

Previously, php-cs-fixer was adding a `\` to *all* constants. I'd like to restore that behavior. Is that possible?

**Comment by Wirone** [comment]
@nicolas-grekas couldn't it be resolved with `include` option? Fixer's description for default config (`fix_built_in=true`) states:

> Whether to fix constants returned by `get_defined_constants`. User constants are not accounted in this list and must be specified in the include one.

so constant must be visible from fixer's point of view during processing in order to fix it automatically. If extension is not installed, there's no constant, hence the behavior you described.

I also saw that you used `strict=false` in related Symfony PR, so maybe it is good enough solution for your needs? There's not much interest in this issue so maybe we could close it 🙂.
