### ISSUE TITLE
OrderedImportsFixer: Alpha sorting so paths are alpha-sorted-grouped and classes are alpha-sorted

### ISSUE THREAD

**Issue by garrettboone** [PHP-CS-Fixer/PHP-CS-Fixer#6339]
## Feature request

Currently alpha sorting breaks slahes into spaces and sorts based on strings. But it does not leave path grouping in order. It would be more orderly to respect subpaths. If this was done then this:
```php
<?php

use App\Concern;
use App\Events\Notifications\VisualNotification;
use App\Events\UpdateQueues;
use App\Location;
use App\Models\Log;
use App\Portal;
use App\Preference;
use App\Repository\ImageRepository;
```

...would become this:
```php
<?php

use App\Concern;
use App\Location;
use App\Portal;
use App\Preference;
use App\Events\Notifications\VisualNotification;
use App\Events\UpdateQueues;
use App\Models\Log;
use App\Repository\ImageRepository;
```

Visually many IDEs color the class differently anyway, and this would emphaize the ordering of paths and then classes in those paths. It's my understanding this is not currently an option.

**Comment by garrettboone** [comment]
Is the team open to a PR on this?

**Comment by SpacePossum** [comment]
Hi and thank you for this suggestion.
I would welcome this feature through a PR, however it is not up to me to make that call :+1:

**Comment by Wirone** [comment]
Hi @garrettboone, thank you for your suggestion. Personally I don't find this kind of ordering useful because IMHO it's not intuitive. For me it does not matter how deep classes are nested in the namespace, that's why I consider class name exactly the same as namespace's segment (directory name).

I am going to close this because:
- proposed ordering is not compatible with "Optimize imports" action in PHPStorm and [VSCode's extension](https://marketplace.visualstudio.com/items?itemName=tarik02.php-imports) (when grouping is disabled)
- I believe this is not widely adopted approach (and it did not get any attention here), so maintaining it in the core is not a good idea

Anyway, if you want to provide implementation and show us how it works in practice (and how much code is needed for that), then go ahead, but remember to keep current default behavior intact (new ordering should be available as opt-in).
