### ISSUE TITLE
[echo_tags_syntax] Add ability to convert php echo tags to `{{ }}` syntax in blade files

### ISSUE THREAD

**Issue by CalebDW** [PHP-CS-Fixer/PHP-CS-Fixer#6537]
## Feature request

The `echo_tags_syntax` fixer currently converts between short and long echo tag formats, however, I have a Laravel project containing blade files with several thousand instances of php echo tags and it would be **super sweet** if the fixer could convert them to the `{{ }}` blade syntax.

**Comment by SpacePossum** [comment]
Sounds like a great case for a Laravel 3d party fixer!

There are a bunch of "official" Laravel repackaging releases of this tool or "providing it as a service" or what not, I suggest it should be fixed there and not here.

**Comment by Wirone** [comment]
Please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), that's why I'm going to close this report.

Also, we try to keep atomic, single-responsibility fixers and converting native `echo` to Blade syntax is IMHO out of the scope of this fixer. As @SpacePossum suggested, it looks like good idea for dedicated package with Laravel-oriented fixers.
