### ISSUE TITLE
Rule Request: named arguments alignment

### ISSUE THREAD

**Issue by iamacarpet** [PHP-CS-Fixer/PHP-CS-Fixer#6627]
## Rule request

We are just starting to use named arguments in PHP8.1

Everything else in our codebase has matching alignment managed by php-cs-fixer.

Named arguments would visually benefit from alignment, but php-cs-fixer currently resets the alignment if we try to do it manually.

### Code snippet that shows how the rule would fix PHP code

```php
        Cookie::queue(
            name: 'basket_count',
            value: 1,
            minutes: config('session.lifetime'),
            httpOnly: false,
        );
```

and we'd like it to be transformed to something like:

```php
        Cookie::queue(
            name:     'basket_count',
            value:    1,
            minutes:  config('session.lifetime'),
            httpOnly: false,
        );
```

**Comment by keradus** [comment]
hey! thanks for your suggestion!
can you share if this style is widely used by any community?

**Comment by Wirone** [comment]
@iamacarpet maybe you could try [`single_space_around_construct`](https://cs.symfony.com/doc/rules/language_construct/single_space_around_construct.html#rule-single-space-around-construct) without `named_argument` in the `constructs_followed_by_a_single_space`? I can't test it right now, but maybe it would leave your manually aligned params?

Personally I don't like such alignments at all, but I understand it would be good to have it consistent.

**Comment by Wirone** [comment]
I am going to close this because:

- it's been a year without significant movement here
- no response to [my suggestion](#issuecomment-1585732995), which works as expected
- we don't have capacity to work on this, as this is not a part of any coding standard that we would like to encourage to use

Last but not least (but maybe little subjectively), this usage of named arguments is just wrong. Named arguments were introduced for scenarios like this:

```php
function foo(bool $a = true, bool $b = true, bool $c = false, bool $d = false): void {}

// Instead of passing all the default values just to change the last one:
foo(true, true, false, true);

// You can now do:
foo(d: true);
```

With named arguments you can skip all the optional arguments (with default value that you don't want to change) and pass only the ones that you want to customise. On the other hand, using named values for every argument does not make sense because:

- it clutters the function call with superfluous information (IDE already can display inlay hints with params' names)
- it makes all the calls error-prone because every signature change requires changes in the function calls too, which makes every diff bigger than it should.

Anyway, if someone is interested in implementing this, we can consider merging this into the core, so feel free to propose a PR (but maybe it would be good to start with a [discussion](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/new?category=feature-ideas)).

**Comment by cviebrock** [comment]
@Wirone Just landed here while searching to see if this is possible.  While I understand your last comment above, I think you might have misinterpreted the request.  Instead of the example method you gave, consider this:
```php
function foo(string $a = 'foo', string $something = 'bar', string $c = 'qua', string $somethingElse = 'non'): void {}

foo(
  a:             'xxx',
  somethingElse: 'yyy',
);
```
I think this was the original intent: not to use _all_ the named arguments necessarily, but when you use any of them, align them on the colon.

I get that it's not part of any standard and that's why it's not being considered at this time.  Just thought I'd clarify what I think the OP was hoping to achieve.

**Comment by Wirone** [comment]
@cviebrock it's hard to tell what OP requested, as `Cookie::queue()`'s signature has only one variadic argument, so using it with named arguments is rather a hack or convention, that actual argument passing. But actually whether all arguments are passed or only some of them is not important in case of this issue being closed, I just provided my opinion about it as an additional feedback, not related directly to the decision about closing this ☺️.
