### ISSUE TITLE
The "no_useless_return" rule causes a unexpected result.

### ISSUE THREAD

**Issue by bluedasher13** [PHP-CS-Fixer/PHP-CS-Fixer#6693]
## Bug report

**Config:**
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->path('/')
    ->in(__DIR__)
;

return (new PhpCsFixer\Config())
    ->setFinder($finder)
    ->setUsingCache(false)
    ->setRules([
        'no_useless_return' => true,
    ]);
```

**Code before fix:**
```php
<?php

function foo() : string {
    return;
}
```

**Code after fix:**
```php
<?php

function foo() : string {
    
}
```

**Result:**
```
Before:
PHP Fatal error:  A function with return type must return a value in #file# on line #line#.

After:
Nothing happend. Unless called "foo()" function, and then I'll get:
PHP Fatal error:  Uncaught TypeError: foo(): Return value must be of type string, none returned in #file#:#line#
```

**Problem:**
When the return type is not "void", if "return;" is kept, I will get a fatal error, whether or not "foo()" is executed.

However, the "no_useless_return" rule causes "return;" to be removed, and the "Fatal error" is no longer appear unless "foo()" was called.

Why is the "no_useless_return" rule non-risky? Shouldn't it be risky?
It caused a change in the result.

**Comment by julienfalque** [comment]
Both functions are wrong and will throw a fatal when called because they do exactly the same thing: returning nothing despite they should return a `string`.

I don't think PHP CS Fixer is wrong when doing this change. It didn't break the code, it only changed the error feedback.

Relying on the presence of the `return` statement to spot the error is a wrong approach IMO. You may want to use a static analysis tool such as PHPStan or Psalm.
