### ISSUE TITLE
`doctrine_annotation_indentation` does't work on a trait's method 

### ISSUE THREAD

**Issue by ruscon** [PHP-CS-Fixer/PHP-CS-Fixer#6723]
### Code snippet that reproduces the problem

This code will not be fixed

  ```php
trait DeleteEntity
{
    /**
     * @OA\Delete(
     *     tags={"Entities"},
     *     path="/entities/{id}",
     *     operationId="deleteEntity",
     *     parameters={
     *          @OA\Parameter(
     *         description="ID of entity to delete",
     *         in="path",
     *         name="id",
     *         required=true,
     *         schema=@OA\Schema(
     *             type="string"
     *         )
     *     )
     * },
     *     responses={
     *           @OA\Response(
     *         response="default",
     *         description="successful operation"
     *     )
     * }
     * )
     */
    public function deleteEntity($id)
    {
    }
}

  ```

**Comment by Wirone** [comment]
It's [by design](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/a2e9e7410792e0532116ba2adfccb9e776d89771/src/AbstractDoctrineAnnotationFixer.php#L242), but I am not sure if we should limit fixer to classes only. Even though [annotations from traits are ignored](https://github.com/doctrine/annotations/issues/216) we still could fix them 🤔. It does not make any difference from Fixer's perspective if such annotations work or not, they're in the file that's being processed and it's possible to apply fixes.

@kubawerlos what do you think?

**Comment by kubawerlos** [comment]
If we decide to support Doctrine's annotation where they do not work then why not support them everywhere?

I'm quite confused as the issue linked claims [https://github.com/doctrine/annotations/issues/216](https://github.com/doctrine/annotations/issues/216) many [web articles](https://www.sitepoint.com/using-traits-doctrine-entities/) show they are not.

**Comment by Wirone** [comment]
Yeah, that's confusing. I didn't verify it because I currently don't work with Doctrine, but whether annotations work with traits or not it does not change what I said - I don't see a point in limiting fixer to classes only.

**Comment by kubawerlos** [comment]
I'd say limiting to only where they work makes sense.

There is no point in doing that for interfaces and enums for sure - they won't work there for sure - but if traits are working then we can support it, if not - let's not waste CPU for that.

**Comment by Wirone** [comment]
Every code that is fixed by Fixer may be a dead code that "does not work" 😉. I would say let's let users decide what they have in their codebase and treat everything like test cases - code must be syntactically correct in order to be fixable, but then don't judge and think too much if it makes sense or not.

**Comment by kubawerlos** [comment]
TBH I don't care much if this will be a feature or not, since I don't remember when was the last time I've create a trait.

I care if that would bring any issues, like people complaining that after the new release, some files will start surprisingly being changed.

@keradus what is your opinion as you are the final sanity voice? :)
@SpacePossum what is yours as you made that limitation? Would it be fine to remove that limit or was it done for some good reason?

**Comment by SpacePossum** [comment]
I've added the `class` check when adding `enum` support, before that it should've worked for `interface`'s and `traits`'s. 
I guess I reasoned that for `enum`'s and `interface`s it would (never'ish) make sense. 
TBH I cannot recall testing for `trait`s and I'm not even 100% now what the current doctrine support status is for `enum` and `traits`'s. 
So not much of an answer you can go on I'm afraid, but I'm sure I didn't but the limitation in because of any technical reason for the app itself.
