### ISSUE TITLE
Output only diff

### ISSUE THREAD

**Issue by hannob** [PHP-CS-Fixer/PHP-CS-Fixer#6784]
## Feature request

I am using php-cs-fixer in a cronjob. What I would like is to get a diff output sent if there is anything to change, and nothing if there's nothing to do. (I.e. I just want the raw diff and nothing else, and if the diff is empty output nothing.)

It seems to me right now this is not possible. I can run
```
php-cs-fixer fix --dry-run --diff [path]
```
This will output the diff, but also various status messages (config/cache/summary). With --quiet it will output nothing.

I could imagine either still outputing the diff when --quiet is passed, as it would make no sense for a user to request both the diff and no output at all. Or one adds another parameter that disables the other messages.

**Comment by kubawerlos** [comment]
Hi @hannob, can you raise PR with a proposed solution?

**Comment by Wirone** [comment]
@hannob instead of running dry run check, you can apply fixes and then leverage `git diff` for that. If your cron job works with production code, you could copy it before applying fixes to not change the running code.

Anyway, it does not look like something that Fixer itself should handle. I'm going to close this, but feel free to provide PR with proposed changes, then we can review it as any other proposal 🙂.
