### ISSUE TITLE
Ban functions, language constructors

### ISSUE THREAD

**Issue by szepeviktor** [PHP-CS-Fixer/PHP-CS-Fixer#6853]
## Feature request

I'd like to prevent usage of things like [`goto` and `var_dump`](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/phpcs.xml#L33-L90).
Like `Squiz.PHP.DiscouragedFunctions` in PHPCS.

How is that possible?

**Comment by kubawerlos** [comment]
PHP CS Fixer is a tool that by design fixes the code.

For `goto` there is no way how to fix it, removing it most likely break functionality, other tools (like PHPStan) can warn you about having `goto`.

For `var_dump` you may want to take a look at [`CommentedOutFunctionFixer`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#CommentedOutFunctionFixer).

**Comment by szepeviktor** [comment]
Thank you.
