### ISSUE TITLE
`no_useless_concat_operator` rule must do nothing when there is a comment between

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6912]
## Bug report

```diff
-$a = 'a' . /* 'b' . */ 'c';
+$a = 'ac' /* 'b' . */;
```

Such transformation can change the meaning of the comment and must never be done.

### Runtime version

any

### Configuration file

`no_useless_concat_operator` with default config

**Comment by kubawerlos** [comment]
> the meaning of the comment

What does it mean? How does removing this comment changes the code?

**Comment by mvorisek** [comment]
> > the meaning of the comment
> 
> What does it mean? How does removing this comment changes the code?

When comment is uncommented, the behaviour will be different.

**Comment by kubawerlos** [comment]
When the comment (I'm assuming you mean code in the comment) is uncommented fixer will work differently.

Since when Fixer should analyse what is in the comment and assume that if it's a code (and a valid one) then work assuming someone might want to uncomment that code?

**Comment by mvorisek** [comment]
Yes, comment position in an AST expression node is important to be preserved as much as possible.

I belive it should be easy to fix to honor comments inside the analysed parenthesised AST node.

**Comment by Wirone** [comment]
I'm going to close this one too because of [the same reasoning](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6911#issuecomment-1520498342) as #6911. We just can't consider comments as potential code that would stop working after uncommenting. It does not make sense for me. I see the point in preserving comments in exact place in signatures (there are for example `/* final */` out there, or commented types), because it works like a warning or information for code consumers. But in your example I believe it should just be removed - commented code is a dead code, since we have Git we don't need to keep such weird structs in the code, we can just remove it and easily revert later (if needed).

I'll try to reach @keradus and if he thinks the other way, we can reopen both issues (as a feature request).
