### ISSUE TITLE
LineLengthFixer: incorrectly takes phpdoc length into account

### ISSUE THREAD

**Issue by Ciki** [PHP-CS-Fixer/PHP-CS-Fixer#6981]
## Bug report

LineLengthFixer: incorrectly takes phpdoc length into account

### Description

```php
<?php

declare(strict_types=1);

class TestClass
{

	/**
	 * This is just standard doc comment for method which declaration's length is actually <  LineLengthFixer max length
	 * but it computes this php doc to the method declaration itself
	 */
	private function testMethod($arg)
	{

	}
}
?>
```

when LineLengthFixer is called on this file, it breaks the line and outputs this

![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/342730/b00405e5-a059-4f34-b7e1-d8931fa0f3d3)

**Comment by kubawerlos** [comment]
Hello @Ciki, are you writing this bug report from the future? Who won the Champions League final?

Can you share the code of `LineLengthFixer`? Because in May 2023 we don't have it yet.

<details>
  <summary>(click in case you are not time traveller)</summary>
 Please run the fixer with "-vvv" option so it displays also the fixer changing the file.
</details>

**Comment by Wirone** [comment]
This fixer comes from [`symplify/coding-standard`](https://github.com/symplify/coding-standard/blob/main/src/Fixer/LineLength/LineLengthFixer.php) and should be reported there 🙂.

**Comment by Wirone** [comment]
/
