### ISSUE TITLE
Static -> self should work with static methods

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7073]
## Feature request

In the following code/example:

```
class Foo
{
    private static function relativizeFilePath(string $dirPath, string $filePath): string
    {
        return 'x';
    }

    public static function makePublicUrlFromFilePath(string $filePath): string
    {
        return = str_replace(rawurlencode('/'), '/', rawurlencode(str_replace(
            \DIRECTORY_SEPARATOR,
            '/',
            static::relativizeFilePath(dirname($_SERVER['SCRIPT_FILENAME']), $filePath)
        )));
    }
}
```

I would expect `static::relativizeFilePath` invocation converted to `self::relativizeFilePath`.

I would expect this to be done by (already existing) `self_static_accessor` rule.

Thankfully, it is detected now at least by phpstan:
```
 998    Unsafe call to private method Foo::relativizeFilePath() through static::.       
```

**Comment by Wirone** [comment]
It is expected behavior. `self_static_accessor` changes `static` to `self` **in private or anonymous classes**. In your case `relativizeFilePath()` still can be implemented in `Foo`'s child class. So yeah, it is technically valid, but discouraged (that's why PHPStan reports it).

**non-final**
<img width="921" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/a3102b15-4f1a-424e-8aa2-8048c245e9b3">

**final**
<img width="921" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/3b74e1e0-76b0-4428-8a4a-760858c560d4">

**Comment by mvorisek** [comment]
I understand your POV, but from OOP design, when you refer private method using `static::`, you do something wrong, so IMHO the fixer, ok, risky one, can fix it safely.

**Comment by Wirone** [comment]
@mvorisek even if it could be done, then issue is clearly wrong because this fixer *already works* with static methods. The problem is somewhere else 🙂.
