### ISSUE TITLE
Incorrect typing definition in `phpdoc_add_missing_param_annotation` rule

### ISSUE THREAD

**Issue by andrey-helldar** [PHP-CS-Fixer/PHP-CS-Fixer#7075]
### Description

When applying the rule for generating dock blocks from parameters, an error is obtained.

### Runtime version

PHP CS Fixer 3.18.0 Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.20

### Used command

PHP CS Fixer is called programmatically from [The Dragon Code Styler](https://github.com/TheDragonCode/codestyler).

### Configuration file
```php
return [
    'phpdoc_add_missing_param_annotation' => [
        'only_untyped' => false,
    ],
];
```

#### Before fix
```php
class PhpdocAddMissingParamAnnotation
{
    /**
     * Some instance.
     */
    public function __construct(
        public ?Throwable $foo = null,
        public readonly ?Throwable $bar = null
    ) {}
}
```

#### After fix
```php
class PhpdocAddMissingParamAnnotation
{
    /**
     * Some instance.
     *
     * @param null|public?Throwable $foo
     * @param null|publicreadonly?Throwable $bar
     */
    public function __construct(
        public ?Throwable $foo = null,
        public readonly ?Throwable $bar = null
    ) {}
}
```

**Comment by Wirone** [comment]
Hi @andrey-helldar, thank you for the report. Even though I don't understand what's the point of adding phpDoc annotations to the method with native types, I know that produced code is invalid 🙂. Looks like it does not work properly with promoted properties, which is not surprising because I believe nobody worked on this fixer for a long time (rather the other way around - on removing superfluous phpDoc). We'll try to fix it, but honestly it won't be a priority task for core team 🙂.
