### ISSUE TITLE
FinalClassFixer doesn't recognize Doctrine entity with repository

### ISSUE THREAD

**Issue by mjanser** [PHP-CS-Fixer/PHP-CS-Fixer#7159]
### Description

The FinalClassFixer should not add `final` to Doctrine entities. But it does when the entity specifies a repository.

The issue is, that https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6893/files#diff-f95af179177c4d274d68caa8361fff580ef6f6928af0ec0e8385dec470db144bL198 switched the annotation check from `starts_with()` to an exact comparison.

### Runtime version

PHP CS Fixer 3.22.0 Chips & Pizza by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.29

### Used command

```
./vendor/bin/php-cs-fixer fix
```

### Configuration file

Nothing special, it includes the FinalClassFixer.

### Code snippet that reproduces the problem

  ```php
<?php
/**
 * @ORM\Entity(repositoryClass="MyRepository")
 */
class MyEntity
{}
  ```

**Comment by SpacePossum** [comment]
Hi,
You might want to swap out this rule for:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.22.0/doc/rules/class_notation/final_internal_class.rst
by default it will not change your file because it checks for the `@ORM\Entity` in the PHPDoc of the class

**Comment by Wirone** [comment]
The problem is in the [regex](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/533d772ac7aa9e7d608093a666a4148e8e3c65ba/src/Fixer/ClassNotation/FinalInternalClassFixer.php#L265) which does not take `(...)` into consideration, so it matches `ORM\Entity(repositoryClass="MyRepository")` and it's not found in the ignored annotations' list. I have fix for annotations, but I need to handle attributes too - I'll finish it in the evening.
