### ISSUE TITLE
`multiline_whitespace_before_semicolons` rule is changing multiline ternary statements

### ISSUE THREAD

**Issue by ampersand** [PHP-CS-Fixer/PHP-CS-Fixer#7229]
### Description

On versions after 3.15 multiline ternary statements are updated by the `multiline_whitespace_before_semicolons` rule. Originally mentioned in comment on #6886 

### Runtime version

PHP CS Fixer 3.23.0 First Steps by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.15

### Configuration file

```php
    'multiline_whitespace_before_semicolons' => [
        'strategy' => 'new_line_for_chained_calls',
    ],
```

### Code snippet that reproduces the problem

Before:
```php
$value = (someCondition())
    ? 'Yes'
    : 'No'
;
```

After:
```php
$value = (someCondition())
    ? 'Yes'
    : 'No';
```

**Comment by ossinkine** [comment]
@ampersand Why do you consider it's a bug? Ternary statement is not a chained calls. It was a bug and fixed in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5126.

**Comment by Wirone** [comment]
I agree with @ossinkine, it's not a bug, because ternary is not a chained call so this strategy does not cover it. Even if it worked before, it was rather coincidence because [there is not any test case for that](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php). It should be rather feature request, but it requires some decision - using strategies probably should be replaced with a set of cases to handle (because one may want to put semicolon in the new line both for chained calls and ternaries, so it can't be disjunctive strategy).

**Comment by ampersand** [comment]
My apologizes on tagging it a bug. Since it didn't start updating multiline ternaries until after v3.15 I assumed it was a bug.

I would love to get this same ability back and not be stuck to v3.15. I can attempt to familiarize myself with the code and submit a PR if you would like.

Would this be an update to an existing rule, or a completely new rule solely for multiline ternaries?
