### ISSUE TITLE
`static_lambda` for immediately released closures is unuseful

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7261]
## Bug report

`static` keyword is helpful for GC as `$this` is not bound.

However, when a closure is passed directly to a known core function like `array_map` or `preg_replace_callback`, the `static` keyword is making the code only more verbose, as the closure is guaranteed to be RC=1 and released immediatelly once the function is finished.

Example:

```php
array_map(function (string $name): string {
    return preg_replace('~\W~', '_', $name);
}, $header)
```

As anonymous functions are used in many heavily used code patterns, I belive the `static_lambda` rule should be fixed to not fix (& unfix) `static` keyword when passed to a core functions than destroy the closure immediately.

**Comment by Wirone** [comment]
I wouldn't call it a bug, because it works even if it's superfluous, that's why I've changed the label and categorised it as enhancement. Also, I am not sure if work required to implement this is worth it - the gain is absolutely minimal and subjective (e.g. I don't have any problem with additional `static`), while the implementation wouldn't be that simple. I'll leave it for now, but I don't think that core team will pick it up anytime soon.

**Comment by mvorisek** [comment]
I would welcome this FR, but I do not want to pursue the implementation.
