### ISSUE TITLE
`YieldFromArrayToYieldsFixer` makes non-equivalent changes

### ISSUE THREAD

**Issue by enumag** [PHP-CS-Fixer/PHP-CS-Fixer#7271]
## Bug report

Consider this code:

```php
function a(): iterable {
    yield from ['a', 'b', 'c'];
    yield from ['d', 'e', 'f'];
};
```

YieldFromArrayToYieldsFixer changes this to:

```php
function a(): iterable {
    yield 'a';
    yield 'b';
    yield 'c';
    yield 'd';
    yield 'e';
    yield 'f';
};
```

In my opinion this change is reasonable. However it is not equivalent as you can see here: https://3v4l.org/OiitA

As such the fixer should be moved from `PhpCsFixerSet` into `PhpCsFixerRiskySet`.

**Comment by Wirone** [comment]
I agree that it's not equivalent when it comes to keys, but if anyone has such `yield from`s like in your example, it most probably means that keys were not consumed anyway. Should we consider it as a bug then? 🤔

**Comment by enumag** [comment]
That's why I think the change is fine for the fixer to make but it is risky nonetheless.

**Comment by Wirone** [comment]
What exact riskiness is here? Consuming such consecutive `yield from` generators with `$key => $value` would be already buggy (potentially doing some logic for some keys twice) or would produce incomplete set of data (when doing `$foo[$key] = ...`). Exactly the same with `iterator_to_array`. Data produced by the unpacked `yield` generators would be the same in terms of values while iterating, but would reveal new keys (however, as I said, most probably they are not used anyway in such code).

Can you provide real world example where this would break something? Because for me it's neither a bug, nor risky change.

**Comment by enumag** [comment]
As you wish.

**Comment by keradus** [comment]
if we have a code sample that may behave differently before applying fixing and after applying fixing, then it's a definition of risky-rule that we have.

with that, I agree it's very edge case, but for it - it is changing the meaning of the code, which constitutes to mark the rule as risky indeed - very nice catch, @enumag !

in theory, we could teach fixer to fix into following sample. or maybe have option for both variants, risky and non-risky:
```
yield 0 => 'a';
yield 1 => 'b';
yield 2 => 'c';
yield 0 => 'd';
yield 1 => 'e';
yield 2 => 'a';
```

**Comment by enumag** [comment]
Yeah... it was my impression that non-risky fixers are supposed to always change the code only in a way that results in an equivalent code without any possible change in the behavior and made the report because this was not the case here strictly speaking... I do not care much about what solution is chosen personally as I'm always using risky fixers in my setup anyway. Just wanted to point it out. :)

**Comment by mvorisek** [comment]
The clean way should be to always unroll /w keys and then fix the keys with https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6617#issuecomment-1235828735 feature request.

**Comment by Wirone** [comment]
These are all fine examples from the generator's perspective, which show what's the technical difference before and after applying fixer, but IMHO it's still academical rather than real-world problem. I am pretty sure that if you do something like:

```php
function a(): iterable {
    yield from u();
    yield from ['d', 'e', 'f'];
};
```

then you're not interested in keys. Any consecutive `yield from` with non-associative array sources looks like value-focused consuming, because you're never sure if keys are duplicated (especially when yielding from function call).

I am interested in examples from consumer's perspective. Where such change would make actual impact and could break the code? In theory every fixer is risky, because you can have code/tests based on reflection, files' checksum etc - every fixer can break your app in specific circumstances. I am still not convinced we should consider it as a bug, but it's only my opinion.

**Comment by keradus** [comment]
> I am interested in examples from consumer's perspective.

i agree it's an edge case


> In theory every fixer is risky, because you can have code/tests based on reflection, files' checksum etc - every fixer can break your app in specific circumstances.

thus, we have a definition what we consider risky and we follow it. And with our own definition and example provided by OP, the rule is risky.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/usage.rst?plain=1#L83
your example with checksum etc does not fit under our definition of what we consider risky or not.
