### ISSUE TITLE
`explicit_indirect_variable` should transform `Cl::$$v`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7442]
## Feature request

repro https://3v4l.org/OsEGa/rfc#vgit.master

dynamic constant fetch is supported since PHP 8.3 - https://wiki.php.net/rfc/dynamic_class_constant_fetch

**Comment by Wirone** [comment]
@mvorisek can you provide explicit examples what should be transformed? Personally I don't get the request here. We can't transform `Foo::$bar` into `Foo::{$bar}` because it would change the intent. The only one case I see that could be covered and I don't see in current test cases is `Foo::$$baz`, but it's handled by the fixer correctly:

<img width="785" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/3d81eafa-27f9-4e53-bb35-89b7ae26af7a">

Well, it even works for dynamic class const fetch on 8.3:

<img width="790" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/1b5cddfc-d16b-428b-a0bd-82e3d1089ff4">

We should update test cases to reflect these cases 🙂.

**Comment by mvorisek** [comment]
`Cl::$v` to `Cl::${$v}`

`Cl::$$v` to `Cl::${$v}` too
