### ISSUE TITLE
statement_indentation on comment  before esle

### ISSUE THREAD

**Issue by gassan** [PHP-CS-Fixer/PHP-CS-Fixer#7454]
## Bug report

```php
function test()
{
    if ('OK') {
        echo 'OK';
-       // OK
+   // OK
    } else {
        echo 'else';
    }
}
```

### Description

comment // OK is intended wrong

### Runtime version

PHP CS Fixer 3.38.2 (c79e006) CI Marathon by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.12

### Used command

php-cs-fixer fix --dry-run --verbose --diff Test.php

### Configuration file

empty

### Code snippet that reproduces the problem

```php
function test()
{
    if ('OK') {
        echo 'OK';
        // OK
    } else {
        echo 'else';
    }
}
```

**Comment by kubawerlos** [comment]
It was once [reported](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6891), then [fixed](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6918) and then [this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7384) PR reintroduced the behavior.

@keradus can you elaborate if it is no longer a bug?

**Comment by Wirone** [comment]
Ha! I was pretty sure I saw such report before, but couldn't find it - was looking for opened ones 😅. I totally forgot it was fixed. Thanks @kubawerlos for the research.

**Comment by keradus** [comment]
I wasn't aware of #6918 :/
It is a matter of what we consider expected output. For me, 6918 was introducing a bug.

I think this is the most representative case of current behaviour, describing when `// comment` will be treated as comment for the `} else` , and when not:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7384/files#diff-68d5723f8971aee572bb313aea1ae350b4e88124c367e63fdcaa1accb40bcbafR992-R1019

I understand different ppl may want to have this comment placed in a different style. I decided to set up expected output as one following the approach of big community we support, Symfony.

If you have a good suggestion how to have a smarter approach for those comments before else, please raise the idea by extending the sample case I linked.

**Comment by Wirone** [comment]
@keradus in the linked example, why comments above `elseif(1)` and `elseif(3)` are handled differently 🤔? IMHO if someone wants to comment if/else branches should do something like this:

```php
// Case 1
if ($foo) {
    echo "foo";
}
// Case 2
elseif(1) {
    echo "bar";
}
// Case 3
elseif(2) {
    // do nothing
}
// Case 4
elseif(3) {
    $aaa = 1;
    // end comment in final block
}
```

I know it's superfluous, but at least explicit when it comes to intent. Comment in the last line of the branch are contextual, they can describe what next branch does or explain what should bo done in the current branch (`@todo`). Personally I would align them as it was already fixed, with the indent, only because (in my opinion) it is more logical.

Anyway, who codes like that 😂.

**Comment by keradus** [comment]
> why comments above elseif(1) and elseif(3) are handled differently 🤔? 

because comment above `elseif(3)` is the only comment in that `{` block

> IMHO if someone wants to comment if/else branches should do something like this:
> }
> // Case 2
> elseif(1) {

- it violates `}` being glued to same line as `elseif`
- big community I was driven this rule for compact are PSR/PER first, and for elements that are not clear on PSR/PER - Symfony. none of those groups are doing it way you suggested

If you prefer to align with PSR/PER or Symfony to get other approach here, please go ahead.
For now, keeping the status quo for the Fixer.

**Comment by Wirone** [comment]
> > why comments above `elseif(1)` and `elseif(3)` are handled differently 🤔?
> 
> because comment above `elseif(3)` is the only comment in that `{` block

@keradus aaaaand 🤔? For me it does not make sense. Consider:

```php
if ($foo) {
    echo "foo";
    // @TODO extend this part with more logic
} elseif($bar) {
    // Do nothing for $bar, but if $baz then let's do this:
} elseif($baz) {
    $aaa = 1;
    // end comment in final block
}
```

With current approach after applying fixer you would get:

```diff
 if ($foo) {
     echo "foo";
-    // @TODO extend $foo part with more logic
+// @TODO extend $foo part with more logic
 } elseif ($bar) {
     // Do nothing for $baz, but if $bar then let's do this:
 } elseif ($baz) {

```

- comment in `if` would be moved, even if it shouldn't
- comment in `elseif($bar)` wouldn't be fixed, even if it's more about next branch (`elseif($baz)`)

Personally I don't like it and I believe sticking to natural indentation (without trying to guess what comment refers to) is much better. If previously suggested approach violates standards, then maybe it should be more like:

```php
if ($foo) {
    // When $foo, then we need to ...
    $someLogic;
} elseif($bar) {
    // For $bar we try to ...
    $moreLogic;
} elseif($baz) {
    // And then, if $baz, we fallback to ...
    $fallbackLogic;
}
```

Anyway, the tool can't guess the intent of the comment, so should apply sane rules. Now it behaves weird IMHO.

**Comment by keradus** [comment]
with your example, i would expect to have the comment above "echo foo". Myself, i also put comment for "else" in "else" itself.
What's sane or not, i know it's debatable, so instead of coming out with "what single person thinks", i (re-)applied what community uses.
"comment before `else` stands for that `else`, same as comment before `if` stands for that `if`", nothing weird in this IMHO
