### ISSUE TITLE
Support php 8.3

### ISSUE THREAD

**Issue by chenrui333** [PHP-CS-Fixer/PHP-CS-Fixer#7465]
👋 while trying to upgrade the homebrew formula to the latest release, I ran into the following failure

```
==> /opt/homebrew/Cellar/php-cs-fixer/3.39.1/bin/php-cs-fixer fix test.php
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.2.*.
Current PHP version: 8.3.0.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
```

Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/155466

**Comment by Wirone** [comment]
Hi @chenrui333, it's not a bug, but expected behaviour. You can follow PHP 8.3 support progress [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/milestone/172), when we are sure that we are compatible with 8.3, we will mark it explicitly as supported. Until then you can use `PHP_CS_FIXER_IGNORE_ENV=1`, our [integration tests](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7439) show that it works OK.
