### ISSUE TITLE
`class_definition` is reformatting phpdoc for anonymous class

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7541]
## Bug report

Code like:
```
$model = new
/**
 * @property string $x
 */
class() extends AtkModel {
    public int $p;
};
```

is currently fixed to:
```
$model = new /**
 * @property string $x
 */ class() extends AtkModel {
    public int $p;
};
```

I would expect no change and all wrongly formatted code fixed to the 1st example.

related with https://github.com/phpstan/phpstan/issues/7345#issuecomment-1848966265

**Comment by Wirone** [comment]
@mvorisek why can't you use [explicit property in anonymous class](https://3v4l.org/gY8db) instead of phpDoc? I am against putting the logic for handling such edge case scenarios in the tools, no matter if it's Fixer or PHPStan. It's just bloating tools' codebase to handle a limited subset of users, when it can be just fixed on their side.

**Comment by mvorisek** [comment]
Because of ORM magic, the property needs to be annotated instead of declared explicitly.

**Comment by Wirone** [comment]
So other tools must bloat their codebase because some ORM requires not optimal way of defining things? Maybe bug in ORM should be created instead? 😉

**Comment by Wirone** [comment]
So other tools must bloat their codebase because some ORM requires not optimal way of defining things? Maybe bug in ORM should be created instead? 😉

**Comment by mvorisek** [comment]
The (changed) code/phpdoc can be still parsed well, but the NL should not be IMHO removed to maintain uniform UX of phpdocs, as normally all phpdocs star on a separate NL and end with separate NL as well.
