### ISSUE TITLE
numeric_literal_separator breaks numbers < 1

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#7736]
original code:

`<?php echo 0.001;`
is modified into
`<?php echo 0._001;`
which is syntax error

**Comment by keradus** [comment]
@muuvmuuv want to take a look, please?

**Comment by muuvmuuv** [comment]
Do you have a few more cases so I can add them all to the tests? Kinda weird that it adds a underscore here.

**Comment by keradus** [comment]
I had previous case, you fixed it, it allowed me to discover new case.
This is not only unexpected that `_` is added, but also making code invalid.

I am not familiar with more failing cases yet, i hope none will be there.

**Comment by muuvmuuv** [comment]
Problem with this case is that I cannot test it actually because the test suite only accepts code to be not the exact match than expected code. Hm, any idea?

Yeah, this one is critical, will try to fix it asap.

**Comment by keradus** [comment]
in data provider, use `expected` param and keep `input` param missing/null

**Comment by Wirone** [comment]
@muuvmuuv Just don't add this case to `yieldCases()` (which provides two-way testing), but provide separate test case like `do not override existing separator`. Or you can modify `yieldCases()` to return `null` instead of input if both are the same. The reason behind `yieldCases()` was to simplify testing for converting in both directions (add or remove separator), but it was prepared for cases where input and expected value was different.

**Comment by muuvmuuv** [comment]
Oh... well :D haven't thought that through well enough

<img width="395" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/11534760/ac4f320d-2736-40b4-81c3-f62b6590be6d">

Hmm. Actually, I don't know how I should "except" this case prior 8.1. Maybe to also check for "dots" in the string but idk sounds dirty/hacky. Any ideas?
