### ISSUE TITLE
Wrong type annotation in Config

### ISSUE THREAD

**Issue by magikid** [PHP-CS-Fixer/PHP-CS-Fixer#7797]
I found [this type error](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/d12282c7a67a25ee87966c34509d5eb4c561af5d/src/Config.php#L58) while working on a custom sniff.  The actual type should be `array<string, array<array-key, mixed>|bool>`.  The reason that the type is wrong is due to [the ordered_class_elements rule](https://cs.symfony.com/doc/rules/class_notation/ordered_class_elements.html#rule-ordered-class-elements).  That rule uses a normal array to specify the ordering of elements and the index is `int`.

**Comment by Wirone** [comment]
@magikid the type is _correct_. In `ordered_class_elements` the "normal array" you're referring to is a set of values available for `order` config option. The reason why they're listed in description, not in an option is because options' output is automated based on definition and there's no way to define "allowed values" (there's only "allowed types" and "default value"). So effectively this is `array<rule-name, array<option-name, option-value>|bool>` (where `bool` is a shortcut for disabling the rule or enabling it with default config).

**Comment by magikid** [comment]
So is this set of rules incorrect then?

```
<?php

namespace Sourceability\CodingStandard;

use PhpCsFixer\Config;
use PhpCsFixer\ConfigInterface;

class PhpCsFixerConfig extends Config
{
    public static function create(): ConfigInterface
    {
        return (new Config())->setRules([
            'ordered_class_elements' => [
                'use_trait',
                'constant_public',
                'constant_protected',
                'constant_private',
                'property_public',
                'property_protected',
                'property_private',
                'construct',
                'destruct',
                'magic',
                'phpunit',
                'method_public',
                'method_protected',
                'method_private',
            ],
        ]);
    }
}
```

**Comment by kubawerlos** [comment]
Have you tried to run it? I guess not, because then you would not ask.

**Comment by Wirone** [comment]
@magikid how hard it to run the actual tool with such config 🤷‍♂️?

```
In AbstractFixer.php line 143:
                                                                                                                                                                                                                        
  [PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException (32)]                                                                                                                                           
  [ordered_class_elements] Invalid configuration: The options "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" do not exist. Defined options are: "case_sensitive", "order", "sort_algorithm". 
```

**Comment by Wirone** [comment]
Bugs require reproducers and you would know it's not a bug if you tried that config before reporting it 😉. I don't know where I was rude - I took my time to verify your report, to respond with complete clarification, but you decided to ask further instead of just run the tool and check it on your side. From maintainers' point of view it's a time-wasting approach, please respect our free time and don't be surprised when there's a little sarcasm involved 😅.
