### ISSUE TITLE
`method_argument_space`: allow separating arguments with empty lines

### ISSUE THREAD

**Issue by raveren** [PHP-CS-Fixer/PHP-CS-Fixer#7849]
## Feature request

https://cs.symfony.com/doc/rules/function_notation/method_argument_space.html

> In method arguments and method call, there MUST NOT be a space before each comma and there MUST be one space after each comma. Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, **the first item** in the list MUST be on the next line, and there MUST be only one argument per line.

This definition allows for empty lines between the two subsequent parameters. Illustrated:

```php
$pageFilters->add(
    Filters\Text::create(/* */),

    Filters\Dropdown::create(
        'user_id',
        /* ... */
    ),

    Filters\Dropdown::create(
        'location_id',
        /* ... */
        /* ... */
        /* ... */
    ),
);
```

IMHO this is a valid, readable way to format variadic function parameters. It's especially useful for more complex ones as they become visually distinct from each other, and that allows cursory scan of the parameters to quickly find the one you need - or to determine the amount of passed parameters, and their order.

However, there is no existing configuration that would allow that, php-cs-fixer removes the empty lines between `Filters` definitions:

```php
$pageFilters->add(
    Filters\Text::create(/* */),
    Filters\Dropdown::create(
        'user_id',
        /* ... */
    ),
    Filters\Dropdown::create(
        'location_id',
        /* ... */
        /* ... */
        /* ... */
    ),
);
```

Thanks for reading and consideration, here's a racoon for your trouble:
```
                ,,,
             .'    `/\_/\
           .'       <@I@>
<((((((((((  )____(  \./
           \( \(   \(\(
            `-"`-"  " "
```

**Comment by Wirone** [comment]
Personally I think it's only over-interpretation of what PSR-12 / PER-CS defines.

> When doing so, the *first item* in the list MUST be on the next line, and there MUST be only one argument per line.

It's defined in coding standards to not allow something like this:

```php
foo($firstArg,
    $secondArg,
    $thirdArg
);
```

and IMHO it unfortunately does not define the spacing between args, leaving the _space_ for interpretation. Examples don't use empty lines between the args though, that's why I think implicit recommendation is _not_ to add empty lines between args. Personally I don't see the value of it too.

Also, Fixer can't know if the function call is variadic or not, as we don't work with AST but with tokens in single file's context, so we just don't know the function's signature when processing the function call (unless it's defined in the same file, but this is still far from reliable).

That's why I am going to close this issue, as we don't plan to work on it. You can always create [custom fixer](https://cs.symfony.com/doc/custom_rules.html) for that.

**Comment by raveren** [comment]
> IMHO 

Thanks for taking the time to type out your answer, no one can argue that you're a hard working individual.

However I'm sorry to burst your self-righteous bubble, but there's nothing humble about your opinions :)

**Comment by Wirone** [comment]
@raveren any counter-arguments for keeping this open, apart from acrimonious remarks?

**Comment by raveren** [comment]
I mean PER and PHPCS are created only for keeping code readable, and you gotta agree, complex parameters are much more readable when separated by new line.

And I also think you have a good insight there, the arguments SHOULD come together if they are not complex expressions.

But is that too much of an edge case for PER to even concern itself with? Maybe. 

Meanwhile, should a code style fixer tool allow both options if not unanimously agreed upon which one is better? I'm pretty sure that it's objectively a "yes".

**Comment by Wirone** [comment]
> you gotta agree, complex parameters are much more readable when separated by new line.

Actually I don't care about these new lines, I don't need them, so I can't agree 🤷.

But it's not about me anyway, I am in the team long enough to know that this issue won't be picked up by any core member, and because of that I don't want to keep this issue open. We can move it to "Feature ideas" discussion, though, so anyone can pick it up if needed. I just don't want to have this issue in the backlog when I am pretty certain that will be there "forever" and I don't want to have to process it once in 3 months when it's marked as stale.
