### ISSUE TITLE
Add double_quote option

### ISSUE THREAD

**Issue by MichaelRushton** [PHP-CS-Fixer/PHP-CS-Fixer#7888]
## Feature request

As a companion to the current `single_quote` option it would be useful to have a `double_quote` option to force single quotes into double quotes.

**Comment by Wirone** [comment]
Sorry, but no. Double quotes are helpful only when you need string interpolation, so using double quotes for all strings is _not_ recommended and definitely shouldn't be promoted by this tool. This can be implemented as custom rule, though (please note it should be marked as risky, if anyone is willing to create it).

**Comment by kubawerlos** [comment]
@MichaelRushton FYI such fixer already exsits: https://github.com/blumilksoftware/codestyle/blob/v2.8.0/src/Fixers/DoubleQuoteFixer.php#L24

**Comment by sylbru** [comment]
I don’t have any issue with this decision, but I’m curious to know more. Why exactly is it not recommended to use double quotes for all strings?

It looks like the performance argument is not relevant anymore, according to [this post from last year](https://dev.to/realflowcontrol/too-double-quote-or-not-thats-the-question-78l).

Or is it because a single-quoted string that would happen to contain variable-like content like `'my $string'` would then become equivalent to `"my {$string}"`, breaking behavior, and there would be no way of preventing that?

**Comment by keradus** [comment]
> or...

[indeed](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7888#issuecomment-1999968851)

**Comment by sylbru** [comment]
I don’t really get it, the comment you’re linking to just says "double quotes for all strings is not recommended" without giving a reason or a source. If the reason actually is what I’m referring to (single-quoted strings containing the `$` character), I can see a couple options:

- convert strings while escaping `$` characters
- only convert strings that don’t contain (unescaped) `$` characters

The first option seems safe to me, but I wouldn’t mind the second option either. One could argue that it’s weird to have a mix of single and double quotes in the codebase. But this very `single_quote` fixer doesn’t see an issue with that: in the following example, only the `$a` line gets changed with the default config, plus the `$b` line if the `strings_containing_single_quote_chars` config is set to true.
```diff
-$a = "simple";
+$a = 'simple';
 $b = "with 'single quotes'";
 $c = "with implicit $variable interpolation";
 $d = "with explicit {$variable} interpolation";
```
```diff
-$a = "simple";
-$b = "with 'single quotes'";
+$a = 'simple';
+$b = 'with \'single quotes\'';
 $c = "with implicit $variable interpolation";
 $d = "with explicit {$variable} interpolation";
```

**Comment by keradus** [comment]
> I don't really get it

from linked post:
> Double quotes are helpful only when you need string interpolation (...)
> This can be implemented as custom rule, though

**Comment by sylbru** [comment]
Yeah and I am now using a custom rule for this. That doesn’t answer my question though: why are we saying it’s "risky" or bad practice without providing any sort of evidence supporting that claim? I’m assuming now that it’s because it’s none of that, just that the maintainers of this project don’t want to implement this option because of stylistic choices. Which is totally fine, really, I just don’t get why we’re inventing fake reasons instead of stating it simply.

**Comment by keradus** [comment]
because
> Double quotes are helpful only when you need string interpolation

So when no interpolation needed, we recommend to not use mechanism for interpolation.
Sorry @sylbru but we clearly have some communication problem. i won't provide you more clarification than one above.
