### ISSUE TITLE
The phpExecutable config is no longer used

### ISSUE THREAD

**Issue by uuf6429** [PHP-CS-Fixer/PHP-CS-Fixer#8028]
### Problem description

It seems that at some point it was possible to set the php binary path in config with `$config->setPhpExecutable`.

While the property and accessors are still there, it seems they're no longer used anywhere:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Config.php#L215

If this was intentional, then I'd suggest removing that config field and its accessors, or at least make the accessors trigger a deprecation warning. If this wasn't intentional....then it needs fixing. 😆 

Usage of the getter was removed here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/8c05b38036c69d07242c73d4b74fe291c90a08b5#diff-c0526b685281b1ce96efcaa2e77ae9658fc6c59b4b40975f5cde342f1678f98dR351 and here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/8c05b38036c69d07242c73d4b74fe291c90a08b5#diff-1ebcd4809ae3308e53be7ae1fa4c0fac3f91631126d21b0653e464436a83fc54L34

### Minimal reproducer

n/a

### Fixer version

3.57.2

### PHP version

8.3

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by uuf6429** [comment]
Additionally, it seems that - unless I'm mistaken - the 3x ProcessLinter* and the CachingLinter classes are no longer used. 🤔 
(they're all marked `@internal` and as far as I can see, one cannot choose a different linter in `\PhpCsFixer\Linter\Linter` or `\PhpCsFixer\Console\ConfigurationResolver::$linter`)

**Comment by Wirone** [comment]
Hi @uuf6429! When it comes to `Config::$phpExecutable` and its getter/setter, you most probably are right that these are not used anywhere. I believe we now use `Symfony\Component\Process\PhpExecutableFinder` and configuration of executable file should be deprecated (it can't be removed as it's a part of `PhpCsFixer\ConfigInterface`).

`CachingLinter` is used in tests (`AbstractFixerTestCase` and `AbstractIntegrationTestCase`), which also internally uses `ProcessLinter` as a sub-linter if `FAST_LINT_TEST_CASES` is not set. Interesting though is that for production usage we always use `Linter` which I find strange, as @keradus always emphasised that linter based on tokenizer is not accurate enough (when I said that `ProcessLinter` takes too much time in CI) 🤔.

> These questions are significant because they would otherwise allow checking/fixing code for a different PHP version than the currently running one.

We can't do this. We need to run Fixer using PHP version it was installed on, because we must be sure our code (and dependencies) are compatible with the runtime. If providing executable (or whole command e.g. for running in Docker) was possible, it would lead to situation where code is executed on unsupported PHP version or using runtime that does not have all the extensions required to work.

**Comment by uuf6429** [comment]
> I believe we now use `Symfony\Component\Process\PhpExecutableFinder`

Are you sure about that? It seems that the config resolver always returns an instance of Linter which then initialises a `TokenizerLinter` unconditionally:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/8f6af012342d215b6b8832e466c15b508ec62d1a/src/Linter/Linter.php#L30

> We need to run Fixer using PHP version it was installed on, because we must be sure our code (and dependencies) are compatible with the runtime.

I think you might have misunderstood... I'd like to change the PHP binary **only** for the linting step.

> If providing executable (or whole command e.g. for running in Docker) was possible, it would lead to situation where code is executed on unsupported PHP version or using runtime that does not have all the extensions required to work.

I don't really get what you mean. From my understanding, php-cs-fixer would run on e.g. PHP 8.3 (with all requirements and everything) and then after fixing files, it ensures they are valid by running `php -l the-changed-file.php`.

So I see no reason why running `php56 -l the-changed-file.php` instead would cause any problems (given that incompatible rules have been disabled).

**Comment by keradus** [comment]
change that brings this question:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/d46dd35170e11d2fba3d9f8b7a3e6057fd924f40#diff-2c4210385b386b8371b68e95ea1ba30a7e276f2d2dbd47d34eda6b2c67d810d6L30-L38

on prd run, if TokenizerLinter is available (which is now always the case), we use it. (otherwise we fallback to ProcessLinter, but no longer needed).
for test run, we know TokenizerLinter is not ideal so we have ProcessLinter there. I'm OK to see if we can rely more on TokenizerLinter in tests and have ProcessLinter for subset of tests (Eg on specific PHP version, or for integration tests only)

**Comment by uuf6429** [comment]
@keradus may I be so bold to suggest allowing the end user to override which linter to use (e.g. via config)?
That would also completely obsolete the `phpExcecutable` field (users could just inject a pre-configured linter instead).
And to a certain extent, it also lessens the pressure on you guys to come up with the "perfect linter that works in all cases".

**Comment by Wirone** [comment]
I said about `PhpExecutableFinder` in `Config::$phpExecutable`'s context, not in linter's. Where we need to specify PHP executable, we use finder, not config's value.

FYI: it was introduced in #1146 and removed in #6298 (without any code review and approval!). I believe it's something to discuss, so anyway thanks for pointing it out.

> I think you might have misunderstood... I'd like to change the PHP binary only for the linting step. (...)

Maybe I am not the one who misunderstood 🙂. You just can't run Fixer on 8.3 and then run `php56 -l the-changed-file.php` because it will fail on any language syntax introduced after PHP 5.6. Lining must be done on the same runtime that is used by main process. It wouldn't even reach fixing stage, as there would be an linting exception before (dispatched `FixerFileProcessedEvent::STATUS_INVALID` in `Runner::fixFile()`).

**Comment by Wirone** [comment]
@uuf6429 for reference, see [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7118#discussioncomment-6356725) and [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7312#discussioncomment-8020855). In general, I understand your point and I agree it would be great to be able to decouple Fixer from PHP runtime, but it's a complex topic.

**Comment by uuf6429** [comment]
> I said about PhpExecutableFinder in Config::$phpExecutable's context, not in linter's. 

Right, I totally understood something else. 👍 

> because it will fail on any language syntax introduced after PHP 5.6. 

Yes, that's why I said the right rules must be disabled. My intention is not to upgrade old source code to a new PHP version.
The intention is that, for example, I run the fixer only for the short-array-syntax rule, in which case anything else should be left as is.

> It wouldn't even reach fixing stage, as there would be an linting exception before

It's understandable the fixer would break or complain for PHP 5.6 syntax features that have been removed. For me that is perfectly fine (in which case we just fix that manually).

**Comment by uuf6429** [comment]
> @uuf6429 for reference, see [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7118#discussioncomment-6356725) and [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7312#discussioncomment-8020855). In general, I understand your point and I agree it would be great to be able to decouple Fixer from PHP runtime, but it's a complex topic.

I think a sophisticated solution as has been discussed there is understandably complex, but what I'm asking for should be relatively simple. 🙈 An alternative that I didn't want to go with is to run `php56 -l ....` after running php-cs-fixer (because then I lose useful logic from php-cs-fixer, such as reverting/not-changing select files, nicer error message etc).
