### ISSUE TITLE
Unable to sort group_import by length

### ISSUE THREAD

**Issue by yaddly** [PHP-CS-Fixer/PHP-CS-Fixer#8035]
### Feature request

Hi PHP-CS-Fixer team, may you please consider adding sorting options to the `group_import` rule.

The default sorting algorithm for `group_import` is `alpha` for alphabetically sorting but there are no other options. I suppose it would be more flexible to give users more control over how `group_import` are sorted, with options such as `['alpha', 'length', 'unsorted']`.

### Contribution Checks

- [ ] I have verified if this feature request was already discussed
- [ ] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
Hi @yaddly! It's sad to see your feature request was not picked up, but please keep in mind that Fixer is maintained voluntarily and we can't implement any idea suggested by users. That's why Github Discussions (especially [feature request section](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/categories/feature-ideas)) were enabled, to collect ideas that does not require triaging and can lead to better Definition of Done. Please start such discussions there in the future 🙂.

Personally I think it would be better if `group_import` didn't do any sorting, but would group in the exact order in which single imports were found, and the sorting was done in `ordered_imports`, where the sorting strategy can already be configured (BTW, it's more or less related to #5347).
