### ISSUE TITLE
May Use the Imports as an Array

### ISSUE THREAD

**Issue by gabrielassuncao77** [PHP-CS-Fixer/PHP-CS-Fixer#8181]
### Problem description

I have been attempting to refactor my project using group imports, but I’ve noticed that they are always formatted as a single long line.

In some cases, we have a maximum line length of 120 characters, so this approach doesn't always work well. It might be more helpful if group imports could be formatted like this instead:

This would likely benefit many developers who face similar constraints. It might also be useful to have a configuration option for this.

### Minimal reproducer

```
<? php

use Space\Models\{
    TestModelA,
    TestModelB,
    TestModel,
};

`````

### Fixer version

3.2

### PHP version

8.3

### How do you run Fixer?

Composer package

### Contribution Checks

- [ ] I have verified if this problem was already reported
- [ ] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by SpacePossum** [comment]
Hi!
Since you didn't share your configuration I'm going to assume you run the tool without one ;)
As such the tool will use the default configuration which includes the rule `single_import_per_statement` which you do not want.

I would recommend making a configuration file so you can exclude this rule. 
Please read https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/config.rst for details, good luck.

**Comment by gabrielassuncao77** [comment]
@SpacePossum, that was exactly it! Thanks a lot! I’ll also include an idea that might help some developers.

**Comment by gabrielassuncao77** [comment]
@SpacePossum, that was exactly it! Thanks a lot!
