### ISSUE TITLE
Reverted ability to set JSON decoder buffer size from 3.59.1?

### ISSUE THREAD

**Issue by cviebrock** [PHP-CS-Fixer/PHP-CS-Fixer#8209]
### Problem description

I reported #8066 back in early June, and @Wirone submitted #8068 as a fix, that eventually made it into release 3.59.1.  This allowed me to increase that buffer in my config, as the old default wasn't enough:
```php
return (new Config())
    ->setParallelConfig(ParallelConfigFactory::detect(null, null, 2**18-1))
    ->setRules([
        ...
```

I'm now working on a project, php-cs-fixer is bumped to 3.64.0, and my IDE is complaining that the `ParallelConfigFactory::detect()` method only has two parameters instead of three.  It looks like that change in 3.59.1 was reverted at some point in the last few months, but I'm having trouble finding where (or why).

In fact, looking at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.59.1/src/Runner/Parallel/ParallelConfigFactory.php#L39, I'm wondering now if this ever got released (although I know that the error I was experiencing in Jenkins was fixed when I bumped my project's requirement to 3.59.1).

Thanks for any information on this!

### Minimal reproducer

Nothing to reproduce; see above for issues/questions.

### Fixer version

3.64.0

### PHP version

8.2

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
It was released, but after [discussion](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8068#pullrequestreview-2099157813) it was implemented as a hardcoded value, significantly higher than before. There's no explicit API for changing this value via configuration. However, @keradus most probably is open to giving the ability to set it via env var, so if you need this, maybe you can provide a PR with such change? I'll close this as this is should be created as a discussion, since it's not an issue.

**Comment by cviebrock** [comment]
Thanks for the update @Wirone !
